(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var A3=function(a){a.ea("cardstatechange",a.Hh()&&a.Jk()?1:0)},B3=function(a,b){var c=g.Oa(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},yUa=function(a){var b=g.Fn(a);
a=g.In(a);return new g.sn(b.x,b.y,a.width,a.height)},zUa=function(a){return Math.pow(a,3)},AUa=function(a){return 3*a*a-2*a*a*a},E3=function(a){a=g.Ra(a);
delete C3[a];g.sf(C3)&&D3&&D3.stop()},CUa=function(){D3||(D3=new g.J(function(){BUa()},20));
var a=D3;a.isActive()||a.start()},BUa=function(){var a=g.Ua();
g.cf(C3,function(b){DUa(b,a)});
g.sf(C3)||CUa()},F3=function(a,b,c,d){g.zr.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.S=b;this.duration=c;this.J=d;this.coords=[];this.progress=this.K=0;this.D=null},DUa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;EUa(a,a.progress);1==a.progress?(a.i=0,E3(a),a.onFinish(),a.bx()):a.Jc()&&a.QC()},EUa=function(a,b){"function"===typeof a.J&&(b=a.J(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.S[c]-a.u[c])*b+a.u[c]},FUa=function(a,b){g.Te.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.i},G3=function(a,b,c,d,e){F3.call(this,b,c,d,e);
this.element=a},H3=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
G3.call(this,a,b,c,d,e)},I3=function(a){g.E.call(this);
this.u=a||window;this.i=[]},J3=function(a){return a.baseUrl||null},K3=function(a,b){return g.Hp(g.Sn(a,b,void 0),function(c){return!!c})},GUa=function(a,b,c){function d(da){var Ba,Ha,ub,Wa=da.hovercardButton;
if(!Wa)return null;Wa=Wa.subscribeButtonRenderer;if(!Wa)return null;var Cb=f(Wa.unsubscribedButtonText),fc=f(Wa.subscribedButtonText);if(Wa.subscribed){var Xa=f(Wa.subscriberCountWithUnsubscribeText);var fd=f(Wa.subscriberCountText)}else Xa=f(Wa.subscriberCountText),fd=f(Wa.subscriberCountWithSubscribeText);var Ob=null;return da.signinEndpoint&&(Ob=B3(da,"signinEndpoint","webNavigationEndpointData","url"),Ob||(Ob=null===(ub=null===(Ha=null===(Ba=Wa.signInEndpoint)||void 0===Ba?void 0:Ba.commandMetadata)||
void 0===Ha?void 0:Ha.webCommandMetadata)||void 0===ub?void 0:ub.url),!Ob)?null:Cb&&(fc||Ob)?{subscribed:Wa.subscribed,subscribeText:Cb,subscribeCount:Xa,unsubscribeText:fc,unsubscribeCount:fd,enabled:Wa.enabled,signinUrl:Ob,classic:da.useClassicSubscribeButton}:null}
function e(da){if(da){var Ba=[],Ha=da.videoId;Ha&&Ba.push("v="+Ha);(Ha=da.playlistId)&&Ba.push("list="+Ha);(da=da.startTimeSeconds)&&Ba.push("t="+da);return"/watch?"+Ba.join("&")}}
function f(da){if(!da)return null;var Ba=da.simpleText;return Ba?Ba:da.runs?g.Sn(da.runs,function(Ha){return Ha.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,v=null,x=!1,y=null,z=null,F=null,I=null,G=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=B3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):z=f(b.subscribersText)}else"WEBSITE"===
h?((F=B3(l,"urlEndpoint","url"))&&(m=F),n=!0,p="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(G=f(b.additionalFeesText)),(n=B3(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=B3(b,"title","accessibility","accessibilityData","label");var M=b.endpoint?b.endpoint.clickTrackingParams:null,Z="";if(b.metadata){var K=f(b.metadata);K&&(Z=K)}return{id:"element-"+c,type:h,title:f(b.title),metadata:Z,callToAction:f(b.callToAction),UK:b.image,
iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:v,subscribeButton:y,subscribersText:z,isSubscribe:x,targetUrl:m||null,cU:n,sessionData:M?{itct:M}:null,OY:p,ev:a?a:null,fU:b.isPlaceholder,impressionUrls:K3(b.impressionUrls||[],J3),ST:K3(b.hovercardShowUrls||[],J3),clickUrls:K3(l.loggingUrls||[],J3),visualElement:g.Gx(b.trackingParams),
productPrice:I,additionalFeesText:G}},L3=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:K3(a.impressionUrls||[],J3),elements:K3(a.elements||[],function(d,e){return GUa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Gx(a.trackingParams));return c},M3=function(a){g.sM.call(this,a);
this.B=this.endscreen=null;this.i={};this.D={};this.C=this.u=null;this.K=[];this.X=!0;this.J=0;a=a.U();this.S=g.$D(a)||g.dE(a);this.events=new g.qC(this);g.H(this,this.events);this.events.T(this.player,g.Ny("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.Oy("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Ab);this.events.T(window,"focus",this.OX);this.load();var b=g.Eh("STYLE");(g.rh("HEAD")[0]||document.body).appendChild(b);g.Se(this,function(){g.Ph(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},HUa=function(a){return a.player.getVideoData().D?"current":a.S?"new":"current"},N3=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},IUa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=L3(f,HUa(a))));O3(a,f)},
urlParams:{v:c},withCredentials:!0};a.S&&(c.urlParams.ptype="embedded");var d=b.Mq;d&&(c.postParams={ad_tracking:d});if(b=g.Tua(b))if(b=g.vg(b),b=g.rg(b))a.B=g.Mt(b,c)},O3=function(a,b,c){c=void 0===c?!0:c;
a.player.hf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.D={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.J=0;if((a.endscreen=b)&&b.elements){c&&JUa(a);c=[];d=new g.Ly(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().isMobile||(a.u=new g.V({G:"div",L:"ytp-ce-shadow"}),g.eM(a.player,a.u.element,4),a.C=new g.LK(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=KUa(a,e);if(f){a.i[e.id]=f;a.D[e.id]=e;g.eM(a.player,f.element,4);var h=new g.Ly(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);LUa(a,
f,e)}else g.Rx(new g.Kv("buildEndscreenElement null",e))}a.player.Od(c);a.Ab()}},JUa=function(a){var b=g.Jx(),c=g.Kx();
c&&b&&a.endscreen.visualElement&&g.Zx(void 0,c,b,[a.endscreen.visualElement])},KUa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.ev||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:P3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:Q3(a,b.targetUrl),tabindex:"-1"},V:[{G:"div",Ia:["ytp-ce-video-title"].concat(g.ma(c)),W:{dir:g.Er(b.title||
"")},va:b.title},{G:"div",L:"ytp-ce-video-duration",va:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.N("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.ev||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",W:P3(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",W:{href:Q3(a,
b.targetUrl),tabindex:"-1"},V:[{G:"div",Ia:["ytp-ce-playlist-title"].concat(g.ma(c)),W:{dir:g.Er(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-playlist-count",V:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",va:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.ev||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",V:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",V:[{G:"div",L:"ytp-ce-expanding-overlay-body",V:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",V:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],W:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Er(b.title||"")},va:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",V:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",va:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],va:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:P3(b)}]};c=new g.V(c);var d=g.sh(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.L(d,"ytp-ce-subscribe-button");if(a.player.U().isMobile){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.vN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.ev||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",V:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",V:[{G:"div",L:"ytp-ce-expanding-overlay-body",V:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",V:[{G:"div",L:"ytp-ce-website-title",W:{dir:g.Er(b.title||"")},va:b.title},{G:"div",L:"ytp-ce-website-metadata",va:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],W:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",W:P3(b)},{G:"div",
L:"ytp-ce-expanding-icon",W:MUa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",V:[{G:"div",L:"ytp-ce-merchandise-price",va:b.productPrice}]},b.additionalFeesText&&c.V.push({G:"div",L:"ytp-ce-merchandise-additional-fees",va:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.ev||"","aria-hidden":"true"},V:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
V:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",V:[{G:"div",L:"ytp-ce-expanding-overlay-body",V:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",V:[{G:"div",L:"ytp-ce-merchandise-title",W:{dir:g.Er(b.title||"")},va:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",va:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:Q3(a,b.targetUrl),target:"_blank",tabindex:"-1"},va:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",W:P3(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",V:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",va:b.callToAction||void 0}]}]},c=new g.V(a)}b.fU&&g.L(c.element,"ytp-ce-placeholder");return c},P3=function(a){if(a.UK)var b=a.UK.thumbnails;
return MUa(b?b[b.length-1].url:null)},MUa=function(a){return a?{style:"background-image: url("+a+")"}:{}},LUa=function(a,b,c){function d(m){m&&(b.Ra("blur",function(){"none"!=m.style.display&&a.X&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.J+=m;0<a.J?(g.L(b.element,"ytp-ce-force-expand"),R3(a,c.id,!0)):(g.qr(b.element,"ytp-ce-force-expand"),g.qr(b.element,"ytp-ce-element-hover"),R3(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Ra("mouseenter",function(){S3(a,b,c)});
b.Ra("mouseleave",function(){T3(a,b,c)});
a.player.U().isMobile||b.Ra("click",function(){g.L(b.element,"ytp-ce-element-hover")});
b.Ra("click",function(m){NUa(a,c,m)});
b.Ra("keypress",function(m){NUa(a,c,m)});
b.Ra("focus",function(){S3(a,b,c)});
b.Ra("blur",function(){T3(a,b,c)});
b.Ra("touchstart",function(){S3(a,b,c)});
var l=g.uh("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.qr(b.element,"ytp-ce-element-hover");g.qr(b.element,"ytp-ce-force-expand")});
b.Ra("keydown",function(m){a.X=9===m.keyCode&&!m.shiftKey});
d(g.uh("ytp-sb-subscribe",b.element));d(g.uh("ytp-sb-unsubscribe",b.element));b.Ra("focus",f);b.Ra("blur",h)},NUa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.or(d,"ytp-ce-element");){g.or(d,"subscribe-label")&&U3(a,b);
if(g.or(d,"ytp-ce-channel-subscribe"))return;d=g.Qh(d)}if(!d||g.or(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])T3(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.OY)U3(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.vg(Q3(a,b.targetUrl)),c=g.rg(c),g.kL(c,void 0,b.sessionData);else{var e=a.player.getVideoData().D,f=function(){var h=Q3(a,b.targetUrl),l=b.sessionData,m=g.wt(h);e&&m&&(m.v||m.list)?a.player.hk(m.v,l,m.list,!1):
g.jL(h,l)};
U3(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},Q3=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.BE(a)+b}else return"";return b},S3=function(a,b,c){g.or(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.L(b.element,"ytp-ce-element-hover"):a.player.U().isMobile?(new g.J(function(){g.L(b.element,"ytp-ce-element-hover")},200)).start():g.L(b.element,"ytp-ce-element-hover"),V3(a,c.ST),R3(a,c.id,!0))},T3=function(a,b,c){g.qr(b.element,"ytp-ce-element-hover");
g.qr(b.element,"ytp-ce-force-expand");R3(a,c.id,!1)},R3=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.N(a.i[e].element,"ytp-ce-element-shadow-show",c)},V3=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||N3(a))c&&c();else{b=OUa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ow(b[a],d)}},U3=function(a,b,c){V3(a,b.clickUrls,c);
(a=g.Kx())&&b.cU&&g.ey(a,b.visualElement)},OUa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(PUa(b[d],c));return a},PUa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},QUa=function(a){return"string"===typeof a?a:""},W3=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},RUa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},X3=function(a){return a.value?a.value:null},Y3=function(a){if(!a)return null;
var b=g.vg(QUa(a.value));b=g.rg(b);if(!b)return null;var c=W3(a.target,SUa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new RUa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},TUa=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},WUa=function(a){if(!a)return null;
var b=W3(a.type,UUa),c=W3(a.trigger,VUa);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=Y3(a?a:null);return b?new TUa(b,c,a):null},XUa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ZUa=function(a){return(a=YUa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},YUa=function(a,b){return g.$b(a.action,b,void 0)},$Ua=function(a,b){this.context=a;
this.i=b},$3=function(a){return a.customMessage?Z3("div","iv-card-message",a.customMessage):""},a4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",L:"iv-card-image",W:{style:a},V:c}},b4=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(Z3("li","",c.value));return{G:"ul",L:"iv-card-meta-info",V:b}},Z3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Er(c);return{G:a,W:b,va:c}},aVa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Py&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Py+");");c.dir=g.Er(a.customMessage);var d=[{G:"span",va:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",Ia:b,W:c,V:d}},c4=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.sessionData,c.tracking.click,5)}},bVa=function(a,b){this.merchant=a;
this.price=b},cVa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},dVa=function(a,b){return b?b:cVa(a)?"current":"new"},d4=function(a,b){g.E.call(this);
var c=this;this.element=a;this.context=b;this.ib=!1;this.Ta=new Map;this.Sa=new Map;this.context.I.addEventListener(g.Ny("annotations_module"),function(d){(d=c.Ta.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.Oy("annotations_module"),function(d){(d=c.Sa.get(d))&&d.apply(c)})},e4=function(a,b,c,d,e,f,h){a.context.i.Ra(b,"click",function(l){a.RC(c,d,e,f||[],h||0,l)});
a.context.i.Ra(b,"touchstart",function(){a.ib=!1});
a.context.i.Ra(b,"touchmove",function(){a.ib=!0})},eVa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},f4=function(a,b,c){return{impression:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
dP:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
HB:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},i4=function(a,b,c){d4.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ka=this.zb=this.B=this.isInitialized=!1;this.ya=null;this.cards=[];this.ob=this.S=this.Ja=this.D=this.Na=this.i=null;this.Z=[];this.K=this.Me=this.Ba=null;this.J=0;this.Aa=new g.J(g.La,c.Y.ze?4E3:3E3);g.H(this,this.Aa);this.bb=new g.J(g.La);g.H(this,this.bb);this.ma=new $Ua(c,function(e,f,h,l,m,n){e4(d,e,f,h,l,m,n)});
this.X=new g.V({G:"div",L:"iv-drawer",W:{id:"iv-drawer"},V:[{G:"div",L:"iv-drawer-header",W:{"aria-role":"heading"},V:[{G:"span",L:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"\u1ea8n th\u1ebb",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.H(this,this.X);this.C=this.X.element;this.Ya=new g.LK(this.X,330);g.H(this,this.Ya);this.qb=g.uh("iv-drawer-header-text",this.C);this.u=g.uh("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.zb&&g4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.zb=d.B)&&h4(d)})},fVa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){g4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){h4(a)});
var c=b.headerText;g.Sh(a.qb,c);a.S&&a.S.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Ba=g.Gx(b.trackingParams);a.K=g.Gx(b.closeTrackingParams);a.Me=g.Gx(b.iconTrackingParams)},gVa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"simple",teaserText:g.Sy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.command),Tl:d.trackingParams?g.Gx(d.trackingParams):null,ej:e.trackingParams?
g.Gx(e.trackingParams):null,Me:f&&f.trackingParams?g.Gx(f.trackingParams):null,imageUrl:k4(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.Sy(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Py:null,title:d.title?g.Sy(d.title):"",customMessage:d.callToAction?g.Sy(d.callToAction):"",url:d.command.urlEndpoint.url?Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};l4(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"collaborator",teaserText:g.Sy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.endpoint),Tl:d.trackingParams?g.Gx(d.trackingParams):null,ej:e.trackingParams?g.Gx(e.trackingParams):null,Me:f&&f.trackingParams?
g.Gx(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.Sy(d.customText):null,profileImageUrl:k4(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.Sy(d.channelName):"",metaInfo:[d.subscriberCountText?g.Sy(d.subscriberCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};
l4(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"playlist",teaserText:g.Sy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.action),Tl:d.trackingParams?g.Gx(d.trackingParams):
null,ej:e.trackingParams?g.Gx(e.trackingParams):null,Me:f&&f.trackingParams?g.Gx(f.trackingParams):null,Wx:k4(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.Sy(d.customMessage):null,playlistVideoCount:g.Sy(d.playlistVideoCount),title:d.playlistTitle?g.Sy(d.playlistTitle):"",metaInfo:[d.channelName?g.Sy(d.channelName):"",d.videoCountText?g.Sy(d.videoCountText):""],url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:eVa(d.action)})};l4(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.videoInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.J,type:"video",teaserText:g.Sy(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:j4(a,c,b,d),sponsored:!1,tracking:f4(d,e,d.action),Tl:d.trackingParams?g.Gx(d.trackingParams):null,ej:e.trackingParams?g.Gx(e.trackingParams):null,Me:f&&f.trackingParams?g.Gx(f.trackingParams):
null,Wx:k4(d.videoThumbnail.thumbnails,258).url,videoDuration:d.lengthString?g.Sy(d.lengthString):null,customMessage:d.customMessage?g.Sy(d.customMessage):null,title:d.videoTitle?g.Sy(d.videoTitle):"",metaInfo:[d.channelName?g.Sy(d.channelName):"",d.viewCountText?g.Sy(d.viewCountText):""],isLiveNow:!!d.badge,url:Y3({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:eVa(d.action)})};l4(a,b)}a.J++},k4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===
a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},j4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},iVa=function(a,b){if(b=hVa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Ph(b.OD),g.hc(a.cards,b),a.Sy(),m4(a)},g4=function(a,b,c){if(!a.B){a.Ya.show();
a.Na=new g.J(function(){g.L(a.context.I.getRootNode(),g.hT.IV_DRAWER_OPEN)},0);
a.Na.start();a.ya=g.zu(a.u,"mousewheel",function(h){a.Aa.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.Kx();d&&a.Ba&&a.K&&g.cy(d,[a.Ba,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.DM||(f.DM=!0,jVa(a.context.logger,f.card.tracking.impression,b)),d&&g.cy(d,[f.card.Tl]);A3(a.I);c&&(a.D=new g.J(function(){a.Ja=a.S;a.ob.focus()},330),a.D.start())}},h4=function(a){a.B&&(a.Ya.hide(),g.Au(a.ya),a.ya=null,g.qr(a.context.I.getRootNode(),g.hT.IV_DRAWER_OPEN),a.B=!1,A3(a.I),a.D&&a.D.stop(),a.D=new g.J(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},
lVa=function(a){g.pr(a.element,[g.hT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.eM(a.I,a.C,5);kVa(a);a.S=g.uh("ytp-cards-button",a.I.getRootNode());a.ob=g.uh("iv-drawer-close-button",a.C);a.isInitialized=!0},kVa=function(a){var b=g.uh("iv-drawer-close-button",a.C);
a.context.i.Ra(b,"click",a.zS,a);a.context.i.Ra(a.u,"touchend",function(){a.Aa.start()});
a.context.i.Ra(a.u,"scroll",a.MS,a);a.context.u.subscribe("onHideControls",function(){a.Ka=!0});
a.context.u.subscribe("onShowControls",function(){a.Ka=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ka=g.or(a.I.getRootNode(),"ytp-autohide")});
a.Z.push(g.Tu("iv-button-shown",a.lU,a));a.Z.push(g.Tu("iv-button-hidden",a.kU,a));a.Z.push(g.Tu("iv-teaser-shown",a.qR,a));a.Z.push(g.Tu("iv-teaser-hidden",a.mU,a));a.Z.push(g.Tu("iv-teaser-clicked",a.pR,a))},l4=function(a,b){a.isInitialized||lVa(a);
iVa(a,b.id);var c=mVa(a,b);if(c){var d={card:b,OD:c.element,DM:!1},e=nVa(a,d);g.nc(a.cards,e,0,d);c.Ea(a.u,e);a.Sy();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.i=d,m4(a),oVa(a,d),g4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&pVa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){pVa(a,d)}),m4(a))}},mVa=function(a,b){switch(b.type){case "simple":a=a.ma;
var c=b.displayDomain?{G:"div",L:"iv-card-image-text",va:b.displayDomain}:void 0;var d=aVa(b);c={G:"div",Ia:["iv-card"],V:[{G:"a",L:"iv-click-target",W:{href:b.url?X3(b.url)||"":""},V:[a4(b.imageUrl,c),{G:"div",L:"iv-card-content",V:[Z3("h2",void 0,b.title),d]}]}]};c=new g.V(c);c4(a,g.th("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.ma,c={G:"div",Ia:["iv-card","iv-card-channel"],V:[{G:"a",Ia:["iv-click-target"],W:{href:X3(b.url)||"","data-ytid":b.channelId},V:[a4(b.profileImageUrl),
{G:"div",L:"iv-card-content",V:[$3(b),{G:"h2",L:"iv-card-primary-link",va:b.title},b4(b)]}]}]},c=new g.V(c),c4(a,g.th("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.ma,c={G:"div",Ia:["iv-card","iv-card-playlist"],V:[{G:"a",L:"iv-click-target",W:{href:X3(b.url)||""},V:[a4(b.Wx,{G:"div",L:"iv-card-image-overlay",V:[{G:"span",L:"iv-card-playlist-video-count",va:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",V:[$3(b),Z3("h2","iv-card-primary-link",b.title),b4(b)]}]}]},c=new g.V(c),
c4(a,g.th("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.ma;var e=!g.dc(b.offers);c=["iv-card"];d="";var f=aVa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({G:"div",L:"iv-card-offer-price",va:f.price}),f.merchant&&e.push({G:"div",L:"iv-card-offer-merchant",va:f.merchant}),f={G:"div",V:e});e=b.url?X3(b.url)||"":"";c={G:"div",Ia:c,W:{tabindex:"0"},V:[{G:"a",Ia:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",V:[b.sponsored?{G:"div",L:"iv-card-sponsored",V:["\u0110\u01b0\u1ee3c t\u00e0i tr\u1ee3",{G:"div",L:"iv-ad-info-container",V:[{G:"div",L:"iv-ad-info",va:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",V:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",W:{href:e},V:[Z3("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Eh("span");g.Sh(d,"B\u1ea1n nh\u00ecn th\u1ea5y s\u1ea3n ph\u1ea9m n\u00e0y v\u00ec ch\u00fang t\u00f4i cho r\u1eb1ng s\u1ea3n ph\u1ea9m c\u00f3 li\u00ean quan \u0111\u1ebfn video. Ng\u01b0\u1eddi b\u00e1n c\u00f3 th\u1ec3 b\u1ed3i th\u01b0\u1eddng cho Google.");
c.Bd(d,"adInfo");c4(a,g.th("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.ma,d=b.videoDuration?{G:"span",L:"iv-card-video-duration",va:b.videoDuration}:void 0,f=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],va:"TR\u1ef0C TI\u1ebeP"}:null,e={G:"div",Ia:["iv-card","iv-card-video"],V:[{G:"a",L:"iv-click-target",W:{href:(null===(c=b.url)||void 0===c?void 0:X3(c))||""},V:[a4(b.Wx,d),{G:"div",L:"iv-card-content",V:[$3(b),Z3("h2","iv-card-primary-link",b.title),b4(b),f]}]}]},
c=new g.V(e),c4(a,g.th("iv-click-target",c.element),b,b.url),c;default:return null}},nVa=function(a,b){if(0===a.cards.length)return 0;
a=g.ac(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},qVa=function(a){return a.i?"productListing"===a.i.card.type:g.Tn(a.cards,function(b){return"productListing"===b.card.type})},m4=function(a){g.N(a.I.getRootNode(),"ytp-cards-shopping-active",qVa(a))},pVa=function(a,b){if(!g.or(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Kx(),d=a.i?a.i.card.Me:a.Me;
c&&d&&g.dy(c,[d]);a.i=b;m4(a)}if(c="none"!=a.element.style.display)c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d;c&&b.card.teaserDurationMs&&a.I.Rt(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.bb.isActive()||((!a.B||!a.Aa.isActive()&&a.Ka)&&oVa(a,b),a.bb.start(910+b.card.teaserDurationMs))}},oVa=function(a,b){a.X.ub?(b=new F3([0,
a.u.scrollTop],[0,b.OD.offsetTop],600,AUa),a.context.B.Ra(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Ra(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.WJ(a.X,!0),a.u.scrollTop=b.OD.offsetTop,g.WJ(a.X,!1))},n4=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},hVa=function(a,b){return g.$b(a.cards,function(c){return c.card.id===b})},o4=function(a,b,c){d4.call(this,a,b);
this.annotation=c;this.isActive=!1},rVa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},p4=function(a,b,c){o4.call(this,a,b,c);
this.u=null;this.K=!1;this.B=null;this.C=!1;this.i=this.J=this.D=null},sVa=function(a,b){var c=void 0===c?0:c;
var d=yUa(b).width;g.Dn(b,d);c=new H3(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,zUa);g.H(a,c);a.context.B.Ra(c,"begin",function(){g.Jn(b,!0)});
c.play()},vVa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],va:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.vN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.I),a.i.Ea(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Jn(h,!1);var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.xn(l,"right",b.image_width+"px");a.element.appendChild(l);a.B=new g.J(function(){tVa(a,h,l)},500);
g.H(a,a.B);a.context.i.Ra(a.element,"mouseover",function(){uVa(a,h,l,f,b.image_height)});
a.context.i.Ra(a.element,"mouseout",function(){a.B.start()})}},uVa=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.In(b);a.i||(b.style.width=g.Cn(f.width,!0),c.style.width=g.Cn(f.width,!0));g.xn(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.xn(d,"right","1px");a.C=!0;g.Jn(b,!0);a.D=new g.J(function(){g.L(this.element,"iv-branding-active")},0,a);
a.D.start()}},tVa=function(a,b,c){g.qr(a.element,"iv-branding-active");
a.J=new g.J(function(){g.Jn(b,!1);a.i||(c.style.width=g.Cn(0,!0))},250);
a.J.start();a.C=!1},wVa=function(a,b,c,d,e,f,h){this.i=a;
this.B=b;this.Y=c;this.videoData=d;this.logger=e;this.I=f;this.u=h},q4=function(a,b,c){o4.call(this,a,b,c);
var d=this;this.S=this.isCollapsed=this.X=!1;this.J=5E3;this.u=this.B=this.i=this.C=null;this.K=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Jn(d.B,!1);g.Jn(d.u,!0)},700,this);
g.H(this,this.D)},xVa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.J=b.collapsedelay_ms||a.J;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Qu\u1ea3ng c\u00e1o");a.element.tabIndex=0;var e=ZUa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",va:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",va:b.playlist_length.toString()}),h.appendChild(f));e&&e4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.Og(f,X3(e)),a.i=f):a.i=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",V:[{G:"strong",
va:b.text_line_1}]});var m=a.createElement({G:"p",V:[{G:"span",L:"iv-promo-link",va:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],V:[{G:"span",L:"iv-button-content",va:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&e4(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.L(a.i,
"iv-click-target");e&&e4(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",V:[{G:"span",va:b.text_line_1}]}),m=a.createElement({G:"p",V:[{G:"strong",va:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],va:"TR\u1ef0C TI\u1ebeP"})),g.L(a.i,"iv-click-target"),e&&e4(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.K.appendChild(a.i);
p&&a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="M\u1edf r\u1ed9ng";a.context.i.Ra(a.u,"click",function(r){r4(a,5E3,r)});
c.appendChild(a.u);g.Jn(a.u,!1);a.context.i.Ra(a.element,"mouseover",a.wT,a);a.context.i.Ra(a.element,"mouseout",a.vT,a);a.context.i.Ra(a.element,"touchend",function(r){r4(a,5E3,r)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="\u0110o\u0301ng";a.context.i.Ra(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.rT:a.qT,a);c.appendChild(a.B);g.pr(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},r4=function(a,b,c){c.stopPropagation();
yVa(a);zVa(a,b);a.i.focus()},AVa=function(a){a.isCollapsed||a.S||a.C||(g.L(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},yVa=function(a){a.D.stop();
a.isCollapsed&&(g.rr(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Jn(a.u,!1),g.Jn(a.B,!0))},zVa=function(a,b){a.C||(a.C=g.Ci(function(){s4(this);
AVa(this)},b,a))},s4=function(a){a.C&&(g.B.clearTimeout(a.C),a.C=null)},BVa=function(a){this.I=a},jVa=function(a,b,c){b&&(c?t4(a,b.map(function(d){return g.Vq(d,c)})):t4(a,b))},t4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Ow(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},u4=function(a){g.sM.call(this,a);
var b=this;this.S=!1;this.loadNumber=0;this.J={};this.logger=new BVa(this.player);this.C=new g.qC(this);this.D=this.Bl=null;this.events=new g.qC(this);this.K=this.i=null;this.X=[];g.H(this,this.C);this.C.T(this.player,"onVideoAreaChange",function(){b.ea("onVideoAreaChange")});
this.C.T(this.player,"onHideControls",function(){b.ea("onHideControls")});
this.C.T(this.player,"onShowControls",function(){b.ea("onShowControls")});
this.C.T(this.player,"resize",function(d){b.ea("resize",d)});
this.C.T(this.player,"presentingplayerstatechange",function(d){b.ea("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.rR,this);this.subscribe("resize",this.MA,this);this.player.U().X.subscribe("vast_info_card_add",this.TN,this);g.H(this,this.events);this.Z=this.createElement({G:"div",L:"video-custom-annotations"});this.u=new g.V({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.H(this,this.u);g.eM(this.player,this.u.element,4);this.u.hide();this.B=new g.V({G:"div",Ia:["ytp-iv-video-content"]});g.H(this,this.B);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.Z);this.B.element.appendChild(a);this.Sq()&&this.load();var c=this.createElement({G:"style"});(g.rh("HEAD")[0]||document.body).appendChild(c);g.Se(this,function(){g.Ph(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},CVa=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.Jn(a,!1);return a},DVa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.WJ(a.u,b);g.WJ(a.B,b)},EVa=function(a,b,c){a.S=!0;
a.D=g.Mt(b,c)},FVa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Pa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(FVa(a,e))}return c},IVa=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().X.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Ft(h)&&h.responseXML?h.responseXML:null)&&v4(a,h)}};
g.bu()&&(d.onFinish=GVa(a,d.onFinish));d.postParams={ic_only:"1"};HVa(d,c);a.S=!0;g.Mt(b.Ta,d)}}},HVa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.xv&&(a.postParams.ic_coll=b.xv);b.Xy&&(a.postParams.ic_xml=b.Xy);b.Zx&&(a.postParams.ic_track=b.Zx)},JVa=function(a){var b=new g.V({G:"div"});
g.Jn(b.element,!1);var c=new i4(a.player,b.element,w4(a));g.H(c,b);b.Ea(a.u.element);c.Ix();return c},w4=function(a){if(!a.K){var b=new I3(a);
g.H(a,b);var c=new g.em(a);g.H(a,c);a.K=new wVa(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.Nd)}return a.K},v4=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Kx();if(e){var f=g.Jx();f&&g.Zx(void 0,e,f,[g.Gx(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=FVa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=W3(f.type,KVa),p=W3(f.style,LVa),r=QUa(f.data),t=0!==r.length?JSON.parse(r):{};var v=f.action;f=WUa;if(null==v)var x=null;else if(g.Oa(v)){l=[];for(var y=g.q(v),z=y.next();!z.done;z=y.next()){var F=f(z.value);
F&&l.push(F)}x=l}else{var I=f(v);x=I?[I]:[]}e=m&&n?new XUa(m,n,p,x,t):null}else e=null}catch(Ba){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var G=CVa(f),M=null;switch(l.type){case "branding":if(f.player.U().Qb)break;f.u.element.appendChild(G);M=new p4(G,w4(f),l);break;case "promotion":g.eM(f.player,G,4),M=new q4(G,w4(f),l)}M&&M.Ix();if(f=M)g.H(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=JVa(a),g.H(a,a.i));if("card"===e.type){c=a.i;var Z=e&&e.data&&e.data.card_type;
f=e.data;if(Z)switch(l=f.tracking||{},l={impression:l.impression,click:l.click,close:l.close,dP:l.teaser_impression,HB:l.teaser_click},G=f.tracking_params||{},M=null,Z){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.Gx(G.card):null,ej:G.teaser?g.Gx(G.teaser):null,Me:G.icon?g.Gx(G.icon):null,
channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,profileImageUrl:f.image_url,title:f.title,metaInfo:f.meta_info,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.Gx(G.card):
null,ej:G.teaser?g.Gx(G.teaser):null,Me:G.icon?g.Gx(G.icon):null,Wx:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "productListing":f.signin_url&&(M=Y3({target:"current",value:f.signin_url}));Z=[];for(var K=f.offers||[],da=0;da<K.length;da++)Z.push(new bVa(g.hh(K[da].merchant),g.hh(K[da].price)));e=
{id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.Gx(G.card):null,ej:G.teaser?g.Gx(G.teaser):null,Me:G.icon?g.Gx(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Py:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),Ifa:M,Hfa:f.signin_title?f.signin_title:void 0,Gfa:f.signin_message?f.signin_message:void 0,offers:Z};l4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.Gx(G.card):null,ej:G.teaser?
g.Gx(G.teaser):null,Me:G.icon?g.Gx(G.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Py:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};l4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,
autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Tl:G.card?g.Gx(G.card):null,ej:G.teaser?g.Gx(G.teaser):null,Me:G.icon?g.Gx(G.icon):null,Wx:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:Y3({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},l4(c,e)}}else fVa(a.i,e);c=!0}}c&&(A3(a.player),a.MA())},MVa=function(a,
b){var c=!1;
a.i||(a.i=JVa(a),g.H(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(gVa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.Sy(b.headerText):"",g.Sh(c.qb,d),c.S&&c.S.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Ba=b.trackingParams?g.Gx(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.Gx(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Me=b.icon.infoCardIconRenderer.trackingParams?
g.Gx(b.icon.infoCardIconRenderer.trackingParams):null,A3(a.player),a.MA())},NVa=function(a,b,c,d,e){if(!a.player.U().Qb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new TUa("openUrl","click",new RUa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.Sy(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.Sy(b.subscriberCountText))):(b.subscriberCountText&&(e=g.Sy(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.Sy(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.Sy(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.Sy(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new XUa(c,"branding","branding",f,d);l=CVa(a);a.u.element.appendChild(l);f=new p4(l,w4(a),f);f.Ix();g.H(f,f);a.J[c]=f}},GVa=function(a,b){return function(){var c=g.Ca.apply(0,arguments);
a.isDisposed()||a.X.push(g.Nu.Vf(function(){b.apply(null,g.ma(c))}))}},OVa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.YL.prototype.Rt=g.ca(18,function(a,b){var c=g.HM(this.vb());c&&c.Rt(a,b)});
var C3={},D3=null;g.Va(F3,g.zr);g.k=F3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.i)this.progress=0,this.coords=this.u;else if(this.Jc())return!1;E3(this);this.startTime=a=g.Ua();-1==this.i&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.IA();this.zi("play");-1==this.i&&this.zi("resume");this.i=1;var b=g.Ra(this);b in C3||(C3[b]=this);CUa();DUa(this,a);return!0};
g.k.stop=function(a){E3(this);this.i=0;a&&(this.progress=1);EUa(this,this.progress);this.zi("stop");this.bx()};
g.k.pause=function(){this.Jc()&&(E3(this),this.i=-1,this.zi("pause"))};
g.k.xa=function(){0==this.i||this.stop(!1);this.zi("destroy");F3.xe.xa.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.QC=function(){this.zi("animate")};
g.k.zi=function(a){this.dispatchEvent(new FUa(a,this))};
g.Va(FUa,g.Te);g.Va(G3,F3);G3.prototype.C=g.La;G3.prototype.QC=function(){this.C();G3.xe.QC.call(this)};
G3.prototype.bx=function(){this.C();G3.xe.bx.call(this)};
G3.prototype.IA=function(){this.C();G3.xe.IA.call(this)};
g.Va(H3,G3);H3.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(I3,g.E);I3.prototype.Ra=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.zu(a,b,c);this.i.push(a);return a};
I3.prototype.sA=function(a,b,c,d){c=(0,g.Sa)(c,d||this.u);a=g.hla(a,b,c);this.i.push(a);return a};
I3.prototype.xc=function(a){g.Au(a);g.hc(this.i,a)};
I3.prototype.xa=function(){g.Au(this.i);this.i.length=0;g.E.prototype.xa.call(this)};g.u(M3,g.sM);g.k=M3.prototype;g.k.load=function(){g.sM.prototype.load.call(this);if(!N3(this)){var a=g.Uua(this.player.getVideoData());a?(a=L3(a,HUa(this)),O3(this,a,!1)):IUa(this)}};
g.k.unload=function(){O3(this,null);this.B&&(this.B.abort(),this.B=null);g.sM.prototype.unload.call(this)};
g.k.uf=function(a,b){return N3(this)?"loadCustomEndscreenRenderer"===a?(a=L3(b,"new"),O3(this,a),!0):null:null};
g.k.getOptions=function(){return N3(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ab=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<PVa.length;f++){var h=Math.abs(b.width-PVa[f]);if(-1===e||d>=h)e=f,d=h}d=QVa[e];this.u&&g.xn(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Hn(e.element,Math.round(h.width*a.width),f);g.Dn(e.element,m,n);g.rr(e.element,RVa);m=h.left+h.width/2;h=h.top+l/2;g.L(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.rr(e.element,QVa);g.L(e.element,d);(e=g.sh(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.xn(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())V3(this,this.endscreen.impressionUrls),(a=g.Kx())&&this.endscreen.visualElement&&g.$x(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.D[a];g.L(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.L(b,"ytp-ce-shown");V3(this,c.impressionUrls);(b=g.Kx())&&g.$x(b,c.visualElement,void 0);this.player.U().B&&this.player.Qa("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.qr(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.qr(b,"ytp-ce-shown");this.player.U().B&&this.player.Qa("endscreenelementhidden",a)}};
g.k.OX=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.rr(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var PVa=[346,426,470,506,570,640,853,1280,1920],QVa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),RVa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var SUa={H3:"current",X9:"new"};var UUa={CLOSE:"close",q$:"openUrl",SUBSCRIBE:"subscribe"},VUa={h0:"click",CLOSE:"close",d5:"hidden",Taa:"rollOut",Uaa:"rollOver",Pba:"shown"};var LVa={i_:"anchored",TP:"branding",CHANNEL:"channel",G3:"cta",g5:"highlightText",I6:"label",PLAYLIST:"playlist",jaa:"popup",Yba:"speech",SUBSCRIBE:"subscribe",qca:"title",VIDEO:"video",Uda:"website"},KVa={TP:"branding",S_:"card",Y3:"drawer",f5:"highlight",l8:"marker",vaa:"promotion",TEXT:"text",yea:"widget"};g.u(d4,g.E);g.k=d4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Ly(a,b,{id:c,namespace:"annotations_module"});d&&this.Ta.set(a,d);e&&this.Sa.set(a,e);this.context.I.Od([a])};
g.k.Ix=function(){this.context.u.subscribe("resize",this.Sy,this)};
g.k.RC=function(a,b,c,d,e,f){if(this.ib)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Ph(this.element)};
g.k.Sy=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=X3(a);if(f){var h=dVa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.D||!1,n=g.wt(f||"");m&&n&&(n.v||n.list)?e.context.I.hk(n.v,b,n.list,!1):g.kL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);t4(this.context.logger,c,l,d);cVa(f)||(c=g.Kx(),d=b.itct,c&&d&&g.ey(c,g.Gx(d)))}};
g.k.xa=function(){this.Ta.clear();this.Sa.clear();g.E.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.u(i4,d4);g.k=i4.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.In(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Sy=function(){var a=this.isAvailable();g.Jn(this.element,a);g.N(this.context.I.getRootNode(),g.hT.IV_DRAWER_ENABLED,a);A3(this.I)};
g.k.destroy=function(){this.I.Rt(!1);try{this.I.getRootNode().removeChild(this.C)}catch(a){}g.Uu(this.Z);g.Au(this.ya);this.Na&&this.Na.dispose();this.D&&this.D.dispose();d4.prototype.destroy.call(this)};
g.k.zS=function(){if(this.B){t4(this.context.logger,n4(this).tracking.close);var a=g.Kx();a&&this.K&&g.ey(a,this.K);h4(this)}};
g.k.MS=function(){g.N(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.lU=function(){var a=g.Kx(),b=n4(this);b=b?b.Me:this.Me;a&&b&&g.cy(a,[b])};
g.k.kU=function(){var a=g.Kx(),b=n4(this);b=b?b.Me:this.Me;a&&b&&g.dy(a,[b])};
g.k.qR=function(){var a=n4(this);t4(this.context.logger,a.tracking.dP);var b=g.Kx();b&&a&&g.cy(b,[a.ej,a.Me])};
g.k.mU=function(){var a=g.Kx(),b=n4(this);a&&b&&g.dy(a,[b.ej])};
g.k.pR=function(a){var b=n4(this),c=g.Kx();this.i?a?(a=this.context.logger,t4(a,b.tracking.HB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.ej&&g.ey(c,b.ej)):(a=this.context.logger,t4(a,b.tracking.HB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Me&&g.ey(c,b.Me)):(a=this.context.logger,t4(a,b.tracking.HB),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Me&&g.ey(c,this.Me))};g.u(o4,d4);o4.prototype.Ix=function(){d4.prototype.Ix.call(this);rVa(this)};
o4.prototype.show=function(){d4.prototype.show.call(this);var a=g.Kx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.cy(a,[g.Gx(b.itct)])};
o4.prototype.hide=function(){d4.prototype.hide.call(this);var a=g.Kx(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.dy(a,[g.Gx(b.itct)])};g.u(p4,o4);
p4.prototype.show=function(){if(!this.isActive){o4.prototype.show.call(this);if(!this.K){g.L(this.element,"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],W:{"aria-label":"H\u00ecnh m\u1edd c\u1ee7a k\u00eanh",src:a.image_url,width:a.image_width,height:a.image_height}});g.Jn(this.u,!1);var b=this.context.Y.N("html5_player_branding_button_killswitch")?this.createElement({G:"div",Ia:["branding-img-container"]}):this.createElement({G:"button",Ia:["branding-img-container",
"ytp-button"]});b.appendChild(this.u);this.element.appendChild(b);var c=ZUa(this.annotation);c&&(b=this.context.Y.N("html5_player_branding_button_killswitch")?this.u:b,e4(this,b,c,this.annotation.id,a.session_data));vVa(this,a);this.K=!0}g.Jn(this.element,!0);this.isActive=!0;this.u&&sVa(this,this.u)}};
p4.prototype.hide=function(){this.isActive&&(o4.prototype.hide.call(this),g.Jn(this.element,!1),this.isActive=!1)};
p4.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);o4.prototype.destroy.call(this)};g.u(q4,o4);g.k=q4.prototype;g.k.show=function(){this.isActive||(o4.prototype.show.call(this),this.X||(xVa(this),this.X=!0),g.Jn(this.element,!0),g.Ci(function(){g.qr(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,s4(this),yVa(this),zVa(this,this.J))};
g.k.hide=function(){this.isActive&&(g.L(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.RC=function(a,b,c,d,e,f){return this.isCollapsed?!1:o4.prototype.RC.call(this,a,b,c,d,e,f)};
g.k.wT=function(a){this.S=!0;r4(this,500,a)};
g.k.vT=function(){this.S=!1;AVa(this)};
g.k.qT=function(a){a.stopPropagation();this.hide()};
g.k.rT=function(a){a.stopPropagation();s4(this);this.isCollapsed=!0;g.L(this.element,"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();o4.prototype.destroy.call(this)};g.u(u4,g.sM);g.k=u4.prototype;g.k.uf=function(a,b){if(!OVa(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.X1(b))&&v4(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(iVa(this.i,b),A3(this.player)),!0}return null};
g.k.getOptions=function(){return OVa(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Sq=function(){var a=this.player.U(),b=this.player.getVideoData();return b.D&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.LM||a.X.get(b.videoId)||g.QF(b)||g.RF(b)?!0:!1};
g.k.MA=function(){if(this.B){var a=this.player.fb().getVideoContentRect(!0);g.Hn(this.B.element,a.width,a.height);g.Dn(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Fj();a=this.i;b=b.width;g.N(a.C,"iv-drawer-small",426>=b);g.N(a.C,"iv-drawer-big",1280<=b)}};
g.k.rR=function(a){DVa(this,a.state);g.U(a.state,2)&&(this.Hh()&&this.Jk()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Rt(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Ft(h)&&h.responseXML?h.responseXML:null)&&(v4(b,h),g.L(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.sM.prototype.load.call(this);DVa(this,this.player.Bb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.bu()&&(a=GVa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().X.get(d);f&&HVa(e,f);f=f&&(f.Xy||f.xv);if(!c.vp||f)c.Ta?EVa(this,c.Ta,e):(this.Bl=function(){b.onVideoDataChange(e)},this.player.addEventListener("videodatachange",this.Bl));
g.eM(this.player,this.B.element,4);this.MA();(f=g.QF(c))&&MVa(this,f);(f=g.RF(c))&&f.featuredChannel&&NVa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&(this.Bl&&(this.player.removeEventListener("videodatachange",this.Bl),this.Bl=null),EVa(this,b.Ta,a))};
g.k.unload=function(){this.player.hf("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.K=null;this.i&&(this.i.destroy(),this.i=null,A3(this.player));this.S=!1;this.D&&(this.D.abort(),this.D=null);this.J={};this.u.hide();g.sM.prototype.unload.call(this);this.B.detach();this.Bl&&(this.player.removeEventListener("videodatachange",this.Bl),this.Bl=null)};
g.k.TN=function(a){a===this.player.getVideoData().videoId&&(this.loaded?IVa(this):this.load())};
g.k.Hh=function(){return!!this.i&&this.i.isAvailable()};
g.k.Jk=function(){this.Hh();return!!this.i&&this.i.B};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Hh();this.i&&(a?c?g4(this.i,c,b):g4(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):h4(this.i))};
g.k.Rt=function(a,b){this.player.ea(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.xa=function(){this.player.U().X.unsubscribe("vast_info_card_add",this.TN,this);g.qr(this.player.getRootNode(),g.hT.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.Nu.wi(a[b]);this.X.length=0;g.sM.prototype.xa.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.H(this,a);return a.element};g.rM("annotations_module",u4);g.rM("creatorendscreen",M3);})(_yt_player);
