(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var i6=function(a,b){if(!Number.isFinite(a))return String(a);a=String(a);var c=a.indexOf(".");-1===c&&(c=a.length);var d="-"===a[0]?"-":"";d&&(a=a.substring(1));return d+(0,g.vSa)("0",Math.max(0,b-c))+a},sXa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.64-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.63 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2z"}}]}},tXa=function(){return{G:"svg",
W:{fill:"#fff",height:"24px",viewBox:"0 0 24 24",width:"24px"},V:[{G:"path",W:{d:"M12 22c1.1 0 2-.9 2-2h-4c0 1.1.9 2 2 2zm6-6v-5c0-3.07-1.63-5.64-4.5-6.32V4c0-.83-.67-1.5-1.5-1.5s-1.5.67-1.5 1.5v.68C7.64 5.36 6 7.92 6 11v5l-2 2v1h16v-1l-2-2zm-2 1H8v-6c0-2.48 1.51-4.5 4-4.5s4 2.02 4 4.5v6z"}}]}},k6=function(a){"number"===typeof a?(this.date=uXa(a,0,1),j6(this,1)):g.Pa(a)?(this.date=uXa(a.getFullYear(),a.getMonth(),a.getDate()),j6(this,a.getDate())):(this.date=new Date(g.Ua()),a=this.date.getDate(),
this.date.setHours(0),this.date.setMinutes(0),this.date.setSeconds(0),this.date.setMilliseconds(0),j6(this,a))},uXa=function(a,b,c){b=new Date(a,b,c);
0<=a&&100>a&&b.setFullYear(b.getFullYear()-1900);return b},j6=function(a,b){a.getDate()!=b&&a.date.setUTCHours(a.date.getUTCHours()+(a.getDate()<b?1:-1))},l6=function(a,b){g.bN.call(this,a,{G:"div",
L:"ytp-reminder-menu",W:{role:"menu",tabindex:"-1"},V:[{G:"div",L:"ytp-reminder-menu-contents",V:[{G:"div",L:"ytp-reminder-menu-items"}]}]},100,!0);this.i=b;this.B=[];this.menuPopupRenderer=void 0;this.items=this.Fa("ytp-reminder-menu-items");this.hide()},wXa=function(a){var b=vXa(a),c=0,d={};
for(c=0;c<b.length;d={eC:d.eC},c++){var e=a.B[c];e||(e=new g.V({G:"div",L:"ytp-reminder-menu-item",W:{role:"menuitem",tabindex:"0"},V:[{G:"div",L:"ytp-reminder-menu-item-icon",va:"{{icon}}"},{G:"div",L:"ytp-reminder-menu-item-label",va:"{{text}}"}]}),d.eC=c,e.Ra("click",function(l){return function(){var m=l.eC;a.Fb();m=vXa(a)[m];a.ea("reminderMenuItemClicked",m.serviceEndpoint||m.command)}}(d)),e.Ea(a.items),a.B[c]=e);
var f=b[c],h=null;switch(f.icon&&f.icon.iconType){case "NOTIFICATIONS":h=sXa();break;case "NOTIFICATIONS_NONE":h=tXa();break;case "NOTIFICATIONS_ACTIVE":h=g.iK()}f=f.text?g.Sy(f.text):"";e.update({icon:h,text:f})}for(;c<a.B.length;)a.B.pop().dispose();0===c?a.Fb():a.kd(a.i)},vXa=function(a){return(a.menuPopupRenderer&&a.menuPopupRenderer.items||[]).reduce(function(b,c){c&&c.menuServiceItemRenderer&&b.push(c.menuServiceItemRenderer);
return b},[])},m6=function(a){g.V.call(this,{G:"div",
V:[{G:"button",Ia:["ytp-offline-slate-button","ytp-button"],V:[{G:"div",L:"ytp-offline-slate-button-icon",va:"{{icon}}"},{G:"div",L:"ytp-offline-slate-button-text",va:"{{text}}"}]}]});this.I=a;this.upcomingEventReminderButtonRenderer=this.toggleButtonRenderer=null;this.u=void 0;this.C=this.i=null;(this.D=this.Fa("ytp-offline-slate-button"))&&this.T(this.D,"click",this.J);this.hide()},xXa=function(a,b,c){!a.toggleButtonRenderer&&b&&b.toggleButtonRenderer?a.toggleButtonRenderer=b.toggleButtonRenderer:
b&&b.toggleButtonRenderer||(a.toggleButtonRenderer=null);
!a.upcomingEventReminderButtonRenderer&&c&&c.upcomingEventReminderButtonRenderer?a.upcomingEventReminderButtonRenderer=c.upcomingEventReminderButtonRenderer:c&&c.upcomingEventReminderButtonRenderer||(a.upcomingEventReminderButtonRenderer=null);n6(a)},n6=function(a){if(a.toggleButtonRenderer){var b=a.toggleButtonRenderer;
if(b.isToggled){var c=b.toggledText?g.Sy(b.toggledText):"";a.update({text:c,icon:o6(b.toggledIcon)})}else c=b.defaultText?g.Sy(b.defaultText):"",a.update({text:c,icon:o6(b.defaultIcon)});a.show()}else a.upcomingEventReminderButtonRenderer?(b=yXa(a))?(c=b.text?g.Sy(b.text):"",a.update({text:c,icon:o6(b.icon)}),a.show()):a.hide():a.hide()},AXa=function(a,b,c){a.C||(a.C=new g.kx(a.I.U().ah));
var d={context:g.nv(a.C.config_||g.ov())};g.Kx()&&(d.context.clientScreenNonce=g.Kx());d.params=c;g.pv(a.C,b,d,{timeout:5E3,onSuccess:function(){a.upcomingEventReminderButtonRenderer&&a.u&&(a.upcomingEventReminderButtonRenderer.currentState=a.u,a.u=void 0)},
onError:function(){zXa(a)},
onTimeout:function(){zXa(a)}})},zXa=function(a){a.toggleButtonRenderer?(a.toggleButtonRenderer.isToggled=!a.toggleButtonRenderer.isToggled,n6(a)):a.upcomingEventReminderButtonRenderer&&(a.u=void 0,n6(a))},o6=function(a){if(!a)return null;
switch(a.iconType){case "NOTIFICATIONS":return sXa();case "NOTIFICATIONS_NONE":return tXa();case "NOTIFICATIONS_ACTIVE":return g.iK();default:return null}},yXa=function(a){if(!a.upcomingEventReminderButtonRenderer)return null;
var b=a.u||a.upcomingEventReminderButtonRenderer.currentState;a=g.q(a.upcomingEventReminderButtonRenderer.states||[]);for(var c=a.next();!c.done;c=a.next())if((c=c.value.upcomingEventReminderButtonStateRenderer)&&c.state===b&&c.button&&c.button.buttonRenderer)return c.button.buttonRenderer;return null},p6=function(a){g.V.call(this,{G:"div",
L:"ytp-offline-slate",V:[{G:"div",L:"ytp-offline-slate-background"},{G:"div",L:"ytp-offline-slate-bar",V:[{G:"span",L:"ytp-offline-slate-icon",V:[{G:"svg",W:{fill:"#fff",height:"100%",viewBox:"0 0 24 24",width:"100%"},V:[{G:"path",W:{d:"M16.94 6.91l-1.41 1.45c.9.94 1.46 2.22 1.46 3.64s-.56 2.71-1.46 3.64l1.41 1.45c1.27-1.31 2.05-3.11 2.05-5.09s-.78-3.79-2.05-5.09zM19.77 4l-1.41 1.45C19.98 7.13 21 9.44 21 12.01c0 2.57-1.01 4.88-2.64 6.54l1.4 1.45c2.01-2.04 3.24-4.87 3.24-7.99 0-3.13-1.23-5.96-3.23-8.01zM7.06 6.91c-1.27 1.3-2.05 3.1-2.05 5.09s.78 3.79 2.05 5.09l1.41-1.45c-.9-.94-1.46-2.22-1.46-3.64s.56-2.71 1.46-3.64L7.06 6.91zM5.64 5.45L4.24 4C2.23 6.04 1 8.87 1 11.99c0 3.13 1.23 5.96 3.23 8.01l1.41-1.45C4.02 16.87 3 14.56 3 11.99s1.01-4.88 2.64-6.54z"}},
{G:"circle",W:{cx:"12",cy:"12",r:"3"}}]}]},{G:"span",L:"ytp-offline-slate-messages",V:[{G:"div",L:"ytp-offline-slate-main-text",W:{"aria-label":"{{label}}"},va:"{{mainText}}"},{G:"div",L:"ytp-offline-slate-subtitle-text",va:"{{subtitleText}}"}]},{G:"span",L:"ytp-offline-slate-buttons"}]},{G:"button",Ia:["ytp-offline-slate-close-button","ytp-button"],V:[g.dK()]},{G:"button",Ia:["ytp-offline-slate-open-button","ytp-button"],V:[g.cK()]},{G:"div",L:"ytp-offline-slate-trailer-chip",va:"\u0110o\u1ea1n gi\u1edbi thi\u1ec7u"}]});
var b=this;this.api=a;this.i=this.u=null;this.background=this.Fa("ytp-offline-slate-background");this.B=this.Fa("ytp-offline-slate-bar");this.D=new g.J(function(){g.L(b.B,"ytp-offline-slate-bar-fade")},15E3);
this.J=!1;this.C=new g.J(function(){g.L(b.element,"ytp-offline-slate-collapsed")},15E3);
g.H(this,this.C);g.H(this,this.D);this.countdownTimer=new g.J(this.xP,1E3,this);this.T(a,"presentingplayerstatechange",this.AP);this.T(a,"livestatedata",this.La);a=this.Fa("ytp-offline-slate-close-button");this.T(a,"click",function(){g.L(b.element,"ytp-offline-slate-collapsed")});
a=this.Fa("ytp-offline-slate-open-button");this.T(a,"click",function(){g.qr(b.element,"ytp-offline-slate-collapsed")});
this.hide();a=this.getVideoData();a.getPlayerResponse()&&(a=a.getPlayerResponse().playabilityStatus)&&this.La(a);a=8===this.api.getPresentingPlayerType()&&!this.getVideoData().qj;var c=8===this.api.getPresentingPlayerType();g.N(this.element,"ytp-offline-slate-premiere-trailer",a);g.N(this.element,"ytp-offline-slate-hide-background",c)},q6=function(a,b,c){var d,e,f,h;
if(b){var l=null!=b.subtitleText?g.Sy(b.subtitleText):"";c=c?c:null!=b.mainText?g.Sy(b.mainText):"";b=null!==(h=null===(f=null===(e=null===(d=b.mainText)||void 0===d?void 0:d.accessibility)||void 0===e?void 0:e.accessibilityData)||void 0===f?void 0:f.label)&&void 0!==h?h:c;a.update({mainText:c,subtitleText:l,label:b});g.N(a.element,"ytp-offline-slate-single-text-line",!l);g.N(a.B,"ytp-offline-slate-bar-hidden",!c&&!l)}},r6=function(a,b){var c=(0,g.Q)();
this.trigger=a;this.i=b;this.B=c},t6=function(a){g.sM.call(this,a);
var b=this;this.K=!1;this.S=0;this.D=!1;this.u=new g.J(function(){var e=b.player.U(),f=b.getVideoData();if(s6(b))if(BXa(b)){var h;null!==(h=b.heartbeatParams)&&void 0!==h&&h.url&&(e=g.Gj(b.heartbeatParams.url,{request_id:g.Jna()}),f.Na&&(e=g.Gj(e,{vvt:f.Na}),f.mdxEnvironment&&(e=g.Gj(e,{mdx_environment:f.mdxEnvironment}))),f.oauthToken&&(e=g.Gj(e,{access_token:f.oauthToken})),CXa(b,f,e))}else DXa(b),EXa(b,e,f)},0);
this.i=this.heartbeatParams=null;this.C=!1;this.J=new g.ij(1E3,6E4,1);this.sequenceNumber=0;this.offlineSlate=null;this.Z=new g.kx(void 0);this.X=this.attestationResponse=void 0;this.utcOffsetMinutes=-(new k6).date.getTimezoneOffset();this.B=new g.qC(this);g.H(this,this.u);g.H(this,this.B);DXa(this);FXa(this);this.B.T(a,"heartbeatparams",this.ex);this.B.T(a,"presentingplayerstatechange",this.GR);this.B.T(a,"videoplayerreset",this.HR);this.B.T(a,g.Ny("heartbeat"),this.onCueRangeEnter);this.C&&this.i&&
GXa(this,this.i);var c=new g.Ly(1E3,0x7ffffffffffff,{priority:1,namespace:"heartbeat"}),d=new g.Ly(0x8000000000000,0x8000000000000,{id:"stream_end",priority:1,namespace:"heartbeat"});a.Od([c,d]);HXa(this)},HXa=function(a){var b=a.getVideoData();
b.Ji&&(b=b.botguardData)&&g.LL(b,a.player.U())},DXa=function(a){var b=a.getVideoData();
if(b.Ji&&(b=new g.Bza(b),g.IL.isInitialized()||3<=a.sequenceNumber)){var c=null;if(b.videoData.Sa){var d=g.Cza(b);if(d){c={};var e={};d=d.split("&");d=g.q(d);for(var f=d.next();!f.done;f=d.next())f=f.value.split("="),2===f.length&&(e[f[0]]=f[1]);e.r1a&&(c.webResponse=e.r1a);e.r1c&&(c.error=IXa[Number(e.r1c)]);c.challenge=b.videoData.Sa}}a.attestationResponse=c||void 0}},BXa=function(a){var b=a.getVideoData();
if(!g.FF(a.getVideoData())||b.uI)return!1;if(b.useInnertubeDrmService()&&b.S){a="playready"===b.S.flavor&&b.N("html5_innertube_heartbeats_for_playready");var c="widevine"===b.S.flavor&&b.N("html5_innertube_heartbeats_for_widevine");b=g.iD(b.S)&&b.N("html5_innertube_heartbeats_for_fairplay");return!(a||c||b)}return!0},u6=function(a){if(BXa(a))return!!a.heartbeatParams;
var b=a.player.U(),c=a.getVideoData();return b.N("html5_heartbeat_wait_for_drm_killswitch")||!g.FF(a.getVideoData())||!c.useInnertubeDrmService()||c.Xg||c.MG?!!c.heartbeatToken:!1},v6=function(a,b){if(!a.u.isActive()&&a.K){var c=a.getVideoData();
if(u6(a)||c.isLivePlayback){if(void 0===b)if(a.D){var d;b=a.C?7500:(null===(d=a.heartbeatParams)||void 0===d?0:d.interval)?1E3*a.heartbeatParams.interval:a.getVideoData().mI||6E4}else b=1E3;a.u.start(b)}}},CXa=function(a,b,c){b.nk&&(c=g.Gj(c,{internalipoverride:b.nk}));
var d={cpn:b.clientPlaybackNonce};b.contextParams&&(d.context_params=b.contextParams);b.yb&&(d.kpt=b.yb);c=g.Gj(c,d);g.Mt(c,{format:"RAW",method:"GET",timeout:3E4,onSuccess:function(e){if(!a.u.isActive()&&s6(a)){a.J.reset();a.sequenceNumber++;e=e.responseText;var f=JXa(e);if(f){a.player.Qa("onHeartbeat",f);var h="ok"===f.status?f.stop_heartbeat?2:0:"stop"===f.status?1:"live_stream_offline"===f.status?0:-1}else h=(h=e.match(KXa))?"0"===h[1]?0:1:-1;LXa(a,f,e,h)}},
onError:function(e){s6(a)&&w6(a,!0,"net-"+e.status)},
onTimeout:function(){s6(a)&&w6(a,!0,"timeout")},
withCredentials:!0})},s6=function(a){var b=a.getVideoData();
return 3===a.player.getPresentingPlayerType()||g.U(a.player.Bb(a.getPlayerType()),4)?!1:u6(a)||b.isLivePlayback?!0:(x6(a),!1)},EXa=function(a,b,c){var d,e,f,h={videoId:c.videoId,
sequenceNumber:a.sequenceNumber,heartbeatServerData:null!==(d=a.ma)&&void 0!==d?d:c.heartbeatServerData};a.X=a.attestationResponse;c.Ji&&(h.attestationResponse=a.X);var l=g.pM(c),m=null!==(e=l.client)&&void 0!==e?e:{};m.utcOffsetMinutes=a.utcOffsetMinutes;h.context=l;h.cpn=c.clientPlaybackNonce;if(l="undefined"!==typeof Intl?(new Intl.DateTimeFormat).resolvedOptions().timeZone:null)m.timeZone=l;m={heartbeatChecks:[]};if(l=c.getPlayerResponse())c.heartbeatToken&&(h.heartbeatToken=c.heartbeatToken),
(l=l.playabilityStatus)&&(l=l.liveStreamability)&&l.liveStreamabilityRenderer&&m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_LIVE_STREAM_STATUS");c.heartbeatToken&&m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_YPC");if(g.tE(b)){m.heartbeatChecks.push("HEARTBEAT_CHECK_TYPE_UNPLUGGED");var n=MXa(a);l={};null!==n&&(l.clientPlayerPositionUtcMillis=n);n=null===(f=a.player.vb())||void 0===f?void 0:g.GM(f);n=(null===n||void 0===n?void 0:n.freePreviewWatchedDuration)||0;0<n&&(l.freePreviewWatchedDuration={seconds:""+
n});m.unpluggedParams=l}h.heartbeatRequestParams=m;b.N("enable_linear_player_handling")&&c.isLivePlayback&&(b=MXa(a),null!==b&&(h.playbackState||(h.playbackState={}),h.playbackState.playbackPosition={utcTimeMillis:b}));b={timeout:3E4,onSuccess:function(p){var r;if(!a.u.isActive()&&s6(a)){var t=a.getVideoData(),v=t.Ji&&null==a.X;t.Ji=!(null===(r=p.heartbeatAttestationConfig)||void 0===r||!r.requiresAttestation)||v;r=p.playabilityStatus;t=JSON.stringify(r)||"{}";p.authenticationMismatch&&a.player.Da("authshear",
{});v=-1;var x=p.playabilityStatus;x&&(a.player.Qa("onHeartbeat",x),"OK"===x.status?v=p.stopHeartbeat?2:0:"UNPLAYABLE"===x.status?v=1:"LIVE_STREAM_OFFLINE"===x.status&&(v=0));a.sequenceNumber&&-1===v||a.J.reset();a.sequenceNumber++;p.heartbeatServerData&&(a.ma=p.heartbeatServerData);LXa(a,r,t,v)}},
onError:function(p){s6(a)&&w6(a,!0,"net-"+p.status)},
onTimeout:function(){s6(a)&&w6(a,!0,"timeout")}};
g.WF(c)&&(b.dK="Bearer "+g.WF(c));g.pv(a.Z,"player/heartbeat",h,b)},LXa=function(a,b,c,d){-1===d?(b="decode "+g.Jc(c),w6(a,!1,b)):2===d?(x6(a),a.D=!0):(a.S=0,a.u.stop(),1===d?(a.D=!1,a.player.Of("heartbeat.stop",a.Ce(c)),g.Fv("heartbeatActionPlayerHalted",NXa(b))):(a.D=!0,c=0,a.C&&b&&(c=GXa(a,b),a.player.ea("livestatedata",b)),c?v6(a,c):v6(a)))},GXa=function(a,b){var c,d,e=b.liveStreamability&&b.liveStreamability.liveStreamabilityRenderer,f=!(!e||!(e.switchStreamsImmediately||e.transitionTiming&&
"STREAM_TRANSITION_TIMING_IMMEDIATELY"===e.transitionTiming)),h=OXa(e),l=a.getVideoData(),m=a.player.Bb(a.getPlayerType()),n=m.Jc()&&!g.KF(l)&&!a.player.isAtLiveHead(a.getPlayerType());
if(2<=l.U().S){var p=(null===(c=a.player.xd())||void 0===c?void 0:c.Mb())||{};p.status=b.status||"";p.dvr=""+ +n;p["switch"]=""+ +f;p.ended=""+ +!(!e||!e.displayEndscreen);a.player.Da("heartbeat",p)}if(n&&!f)return h;f=e&&e.streamTransitionEndpoint&&e.streamTransitionEndpoint.watchEndpoint;if("STREAM_TRANSITION_TIMING_AT_STREAM_END"===(e&&e.transitionTiming))a.getVideoData().zM=f;else{if(n=f)(n=f&&f.videoId)?(a.player.hk(n,{autonav:"1"},void 0,!0,!0,f),a.uA("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT",
b),n=!0):n=!1;if(n)return h}if("OK"===b.status.toUpperCase()){f=e&&e.broadcastId;n=a.i&&a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer&&a.i.liveStreamability.liveStreamabilityRenderer.broadcastId;p=f!==n&&(null!=f||a.player.N("web_player_heartbeat_undefined_killswitch"));if(!l.hlsvp&&!l.qb||p)return e={video_id:l.videoId},l.nC&&(e.is_live_destination="1"),a.player.N("web_player_heartbeat_request_watch_next")||(e.disable_watch_next=!0,e.raw_watch_next_response=l.watchNextResponse),
e.autonav_state=l.autonavState,e.oauth_token=l.oauthToken,e.force_gvi=l.ah,e.Fi=l.Fi,8===a.player.getPresentingPlayerType()&&a.player.So(8),m=void 0,l.hlsvp||l.qb?p&&(m=new r6("broadcastIdChanged",n+","+f),a.uA("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_BROADCAST_ID_CHANGED",b)):(f&&(m=new r6("formatsReceived",""+f)),a.uA("HEARTBEAT_ACTION_TRIGGER_IMMEDIATE","HEARTBEAT_ACTION_TRANSITION_REASON_LIVE_STREAM_WENT_ONLINE",b)),a.player.loadVideoByPlayerVars(e,void 0,void 0,
void 0,m),h;a.player.Ge("heartbeat",a.getPlayerType())}e&&e.displayEndscreen&&(a.offlineSlate?(a=a.offlineSlate,a.J=!0,a.ub&&a.api.Ut()):g.WI(m)&&(l=(null===(d=a.player.xd())||void 0===d?void 0:d.Mb())||{},a.player.Da("hbse",l,!0),a.player.Ut(),a.player.Qa("onLiveMediaEnded",b)));return h},OXa=function(a){var b=0;
a&&a.pollDelayMs&&(a=Number(a.pollDelayMs))&&(b=a);return b},w6=function(a,b,c){if(!a.u.isActive()){a.u.stop();
a.S++;var d=a.getVideoData();if(d.oI||b&&!g.FF(a.getVideoData())&&!u6(a)&&d.isLivePlayback)var e=!1;else{var f;(null===(e=a.heartbeatParams)||void 0===e?0:e.Dx)?f=a.heartbeatParams.Dx:f=d.nI||5;e=a.S>=f}e?(b?(b="heartbeat.net",e={enforcedPolicyToHaltOnNetworkFailure:!0}):(b="heartbeat.servererror",e=NXa()),g.Fv("heartbeatActionPlayerHalted",e),(e=a.getVideoData())&&e.isLivePlayback?a.player.Of(b,"Ph\u00e1t l\u1ea1i video b\u1ecb gi\u00e1n \u0111o\u1ea1n. Vui l\u00f2ng th\u1eed l\u1ea1i.",c):a.player.Of(b,
"R\u1ea5t ti\u1ebfc, \u0111\u00e3 x\u1ea3y ra l\u1ed7i khi c\u1ea5p ph\u00e9p video n\u00e0y.",c)):(v6(a,a.J.getValue()),g.jj(a.J))}},NXa=function(a){var b={enforcedPolicyToHaltOnNetworkFailure:!1};
a&&(b.serializedServerContext=a.additionalLoggingData);return b},x6=function(a){a.S=0;
a.u.stop();a.D=!1;a.sequenceNumber=0},FXa=function(a){var b,c=a.getVideoData(),d=a.player.U();
if(c.isLivePlayback)if(g.qD(d.u)){a.C=!0;a.K=!0;if(!g.iE(d)||g.tE(d))a.offlineSlate=new p6(a.player),g.H(a,a.offlineSlate),g.eM(a.player,a.offlineSlate.element,4);(c=c.getPlayerResponse())&&c.playabilityStatus&&(a.i=c.playabilityStatus);if("UNPLAYABLE"!==(null===(b=a.i)||void 0===b?void 0:b.status)||a.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch"))a.i?(c=OXa(a.i.liveStreamability&&a.i.liveStreamability.liveStreamabilityRenderer))?v6(a,c):v6(a,7500):v6(a,1E3)}else a.player.Of("html5.unsupportedlive",
"HTML5_NO_AVAILABLE_FORMATS_FALLBACK","nolive.1");else!d.N("html5_release_post_live_heartbeat_killswitch")&&g.cc(c.ya,"heartbeat")&&a.player.Ge("heartbeat",a.getPlayerType())},MXa=function(a){return(a=a.player.getProgressState(a.getPlayerType()).ingestionTime)&&isFinite(a)?""+Math.floor(1E3*a):null},JXa=function(a){try{var b=JSON.parse(a);
return null!=b?b:void 0}catch(c){}},IXa=["ATTESTATION_ERROR_UNKNOWN",
"ATTESTATION_ERROR_VM_NOT_INITIALIZED","ATTESTATION_ERROR_VM_NO_RESPONSE","ATTESTATION_ERROR_VM_TIMEOUT","ATTESTATION_ERROR_VM_INTERNAL_ERROR"],y6={ERAS:["BC","AD"],ERANAMES:["Before Christ","Anno Domini"],NARROWMONTHS:"JFMAMJJASOND".split(""),STANDALONENARROWMONTHS:"JFMAMJJASOND".split(""),MONTHS:"January February March April May June July August September October November December".split(" "),STANDALONEMONTHS:"January February March April May June July August September October November December".split(" "),
SHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),STANDALONESHORTMONTHS:"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" "),WEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),STANDALONEWEEKDAYS:"Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),SHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),STANDALONESHORTWEEKDAYS:"Sun Mon Tue Wed Thu Fri Sat".split(" "),NARROWWEEKDAYS:"SMTWTFS".split(""),STANDALONENARROWWEEKDAYS:"SMTWTFS".split(""),
SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["1st quarter","2nd quarter","3rd quarter","4th quarter"],AMPMS:["AM","PM"],DATEFORMATS:["EEEE, MMMM d, y","MMMM d, y","MMM d, y","M/d/yy"],TIMEFORMATS:["h:mm:ss a zzzz","h:mm:ss a z","h:mm:ss a","h:mm a"],DATETIMEFORMATS:["{1} 'at' {0}","{1} 'at' {0}","{1}, {0}","{1}, {0}"],FIRSTDAYOFWEEK:6,WEEKENDRANGE:[5,6],FIRSTWEEKCUTOFFDAY:5};
y6={ERAS:["Tr\u01b0\u1edbc CN","Sau CN"],ERANAMES:["Tr\u01b0\u1edbc Thi\u00ean Ch\u00faa","Sau C\u00f4ng Nguy\u00ean"],NARROWMONTHS:"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),STANDALONENARROWMONTHS:"1 2 3 4 5 6 7 8 9 10 11 12".split(" "),MONTHS:"th\u00e1ng 1;th\u00e1ng 2;th\u00e1ng 3;th\u00e1ng 4;th\u00e1ng 5;th\u00e1ng 6;th\u00e1ng 7;th\u00e1ng 8;th\u00e1ng 9;th\u00e1ng 10;th\u00e1ng 11;th\u00e1ng 12".split(";"),STANDALONEMONTHS:"Th\u00e1ng 1;Th\u00e1ng 2;Th\u00e1ng 3;Th\u00e1ng 4;Th\u00e1ng 5;Th\u00e1ng 6;Th\u00e1ng 7;Th\u00e1ng 8;Th\u00e1ng 9;Th\u00e1ng 10;Th\u00e1ng 11;Th\u00e1ng 12".split(";"),
SHORTMONTHS:"thg 1;thg 2;thg 3;thg 4;thg 5;thg 6;thg 7;thg 8;thg 9;thg 10;thg 11;thg 12".split(";"),STANDALONESHORTMONTHS:"Thg 1;Thg 2;Thg 3;Thg 4;Thg 5;Thg 6;Thg 7;Thg 8;Thg 9;Thg 10;Thg 11;Thg 12".split(";"),WEEKDAYS:"Ch\u1ee7 Nh\u1eadt;Th\u1ee9 Hai;Th\u1ee9 Ba;Th\u1ee9 T\u01b0;Th\u1ee9 N\u0103m;Th\u1ee9 S\u00e1u;Th\u1ee9 B\u1ea3y".split(";"),STANDALONEWEEKDAYS:"Ch\u1ee7 Nh\u1eadt;Th\u1ee9 Hai;Th\u1ee9 Ba;Th\u1ee9 T\u01b0;Th\u1ee9 N\u0103m;Th\u1ee9 S\u00e1u;Th\u1ee9 B\u1ea3y".split(";"),SHORTWEEKDAYS:"CN;Th 2;Th 3;Th 4;Th 5;Th 6;Th 7".split(";"),
STANDALONESHORTWEEKDAYS:"CN;Th 2;Th 3;Th 4;Th 5;Th 6;Th 7".split(";"),NARROWWEEKDAYS:"CN T2 T3 T4 T5 T6 T7".split(" "),STANDALONENARROWWEEKDAYS:"CN T2 T3 T4 T5 T6 T7".split(" "),SHORTQUARTERS:["Q1","Q2","Q3","Q4"],QUARTERS:["Qu\u00fd 1","Qu\u00fd 2","Qu\u00fd 3","Qu\u00fd 4"],AMPMS:["SA","CH"],DATEFORMATS:["EEEE, d MMMM, y","d MMMM, y","d MMM, y","dd/MM/y"],TIMEFORMATS:["HH:mm:ss zzzz","HH:mm:ss z","HH:mm:ss","HH:mm"],DATETIMEFORMATS:["{0} {1}","{0} {1}","{0}, {1}","{0}, {1}"],FIRSTDAYOFWEEK:0,WEEKENDRANGE:[5,
6],FIRSTWEEKCUTOFFDAY:6};g.k=k6.prototype;g.k.dL=y6.FIRSTDAYOFWEEK;g.k.eL=y6.FIRSTWEEKCUTOFFDAY;g.k.clone=function(){var a=new k6(this.date);a.dL=this.dL;a.eL=this.eL;return a};
g.k.getFullYear=function(){return this.date.getFullYear()};
g.k.getMonth=function(){return this.date.getMonth()};
g.k.getDate=function(){return this.date.getDate()};
g.k.set=function(a){this.date=new Date(a.getFullYear(),a.getMonth(),a.getDate())};
g.k.add=function(a){if(a.u||a.i){var b=this.getMonth()+a.i+12*a.u,c=this.getFullYear()+Math.floor(b/12);b%=12;0>b&&(b+=12);a:{switch(b){case 1:var d=0!=c%4||0==c%100&&0!=c%400?28:29;break a;case 5:case 8:case 10:case 3:d=30;break a}d=31}d=Math.min(d,this.getDate());this.date.setDate(1);this.date.setFullYear(c);this.date.setMonth(b);this.date.setDate(d)}a.days&&(c=this.getFullYear(),b=0<=c&&99>=c?-1900:0,a=new Date((new Date(c,this.getMonth(),this.getDate(),12)).getTime()+864E5*a.days),this.date.setDate(1),
this.date.setFullYear(a.getFullYear()+b),this.date.setMonth(a.getMonth()),this.date.setDate(a.getDate()),j6(this,a.getDate()))};
g.k.equals=function(a){return!(!a||this.getFullYear()!=a.getFullYear()||this.getMonth()!=a.getMonth()||this.getDate()!=a.getDate())};
g.k.toString=function(){var a=this.getFullYear(),b=0>a?"-":1E4<=a?"+":"";return[b+i6(Math.abs(a),b?6:4),i6(this.getMonth()+1,2),i6(this.getDate(),2)].join("")+""};
g.k.valueOf=function(){return this.date.valueOf()};g.u(l6,g.bN);l6.prototype.hide=function(){this.i&&this.i.removeAttribute("aria-haspopup");g.bN.prototype.hide.call(this)};
l6.prototype.show=function(){this.i&&this.i.setAttribute("aria-haspopup","true");g.bN.prototype.show.call(this)};
l6.prototype.xa=function(){g.Re(this.B);g.bN.prototype.xa.call(this)};g.u(m6,g.V);
m6.prototype.J=function(){if(this.toggleButtonRenderer){var a=this.toggleButtonRenderer;a.isToggled?this.B(a.toggledServiceEndpoint):this.B(a.defaultServiceEndpoint);a.isToggled=!a.isToggled;n6(this)}else if(this.upcomingEventReminderButtonRenderer)if(this.i&&this.i.ub)this.i.Fb();else{var b=yXa(this);b&&this.B(b.serviceEndpoint||b.command);b=g.q(b&&b.command&&b.command.commandExecutorCommand&&b.command.commandExecutorCommand.commands||[]);for(var c=b.next();!c.done;c=b.next())if((c=c.value)&&c.openPopupAction&&
c.openPopupAction.popup&&c.openPopupAction.popup.menuPopupRenderer){a=c.openPopupAction.popup.menuPopupRenderer;break}this.i||(this.i=new l6(this.I,this.D),this.i.Ea(this.element),g.H(this,this.i),this.i.subscribe("reminderMenuItemClicked",this.B,this));b=this.i;b.menuPopupRenderer=a;wXa(b)}};
m6.prototype.B=function(a){if(a&&(a.addUpcomingEventReminderEndpoint||a.removeUpcomingEventReminderEndpoint)){if(a.addUpcomingEventReminderEndpoint){var b=a.addUpcomingEventReminderEndpoint;var c="notification/add_upcoming_event_reminder"}else a.removeUpcomingEventReminderEndpoint&&(b=a.removeUpcomingEventReminderEndpoint,c="notification/remove_upcoming_event_reminder");if(c&&b&&b.params)for(AXa(this,c,b.params),a=g.q(b.commands||[]),b=a.next();!b.done;b=a.next())if((b=b.value)&&b.updateUpcomingEventReminderButtonStateCommand){this.u=
b.updateUpcomingEventReminderButtonStateCommand.state;n6(this);break}}};g.u(p6,g.V);g.k=p6.prototype;g.k.getPlayerType=function(){if(8===this.api.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.api.getVideoData(this.getPlayerType())};
g.k.La=function(a){var b,c,d=null===(c=null===(b=null===a||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate;if(d){this.u=a;d=d.liveStreamOfflineSlateRenderer;d.canShowCountdown?this.xP():q6(this,d);var e,f,h,l,m=null===(l=null===(h=null===(f=null===(e=null===a||void 0===a?void 0:a.liveStreamability)||void 0===e?void 0:e.liveStreamabilityRenderer)||void 0===f?void 0:f.offlineSlate)||void 0===h?void 0:h.liveStreamOfflineSlateRenderer)||
void 0===l?void 0:l.thumbnail;if(m){e=0;f=null;m=m.thumbnails;for(h=0;h<m.length;h++)m[h].width>e&&(e=m[h].width||0,f=m[h].url);f&&(this.background.style.backgroundImage="url("+f+")")}else this.background.style.backgroundImage="";d.actionButtons||d.reminderButton?(this.i||(this.i=new m6(this.api),this.i.Ea(this.Fa("ytp-offline-slate-buttons")),g.H(this,this.i)),xXa(this.i,d.actionButtons&&d.actionButtons[0],d.reminderButton)):this.i&&xXa(this.i,null,null);this.u=a}else this.u=null;this.AP()};
g.k.AP=function(a){if(8===this.api.getPresentingPlayerType())var b=!0;else{var c=this.api.Bb(),d=this.getVideoData();b=d.isLivePlayback&&(g.WI(c)||g.U(c,2)||g.U(c,64));var e=2===d.autonavState&&g.U(c,2);c=c.Jc()&&!g.KF(d)&&!this.api.isAtLiveHead(void 0,!0);b=b&&!c&&!e}b&&this.u?this.ub?(null===a||void 0===a?0:g.TG(a,2))&&!this.getVideoData().qj&&(g.qr(this.element,"ytp-offline-slate-collapsed"),this.C.stop(),g.qr(this.B,"ytp-offline-slate-bar-fade"),this.D.start()):(this.show(),this.C.start(),this.api.ea("offlineslatestatechange"),
this.J&&this.api.Ut()):this.ub&&(this.hide(),this.api.ea("offlineslatestatechange"))};
g.k.xP=function(){var a,b,c,d,e=null===(d=null===(c=null===(b=null===(a=this.u)||void 0===a?void 0:a.liveStreamability)||void 0===b?void 0:b.liveStreamabilityRenderer)||void 0===c?void 0:c.offlineSlate)||void 0===d?void 0:d.liveStreamOfflineSlateRenderer;if(e){var f=Math.floor(g.Ua()/1E3),h=e.canShowCountdown&&Number(e.scheduledStartTime);!h||h<=f?(q6(this,e),this.countdownTimer.stop()):(f=g.ZK(h-f),q6(this,e,f),g.ar(this.countdownTimer))}};
g.k.xa=function(){this.countdownTimer.dispose();this.countdownTimer=null;g.V.prototype.xa.call(this)};r6.prototype.u=function(a){return this.trigger&&a.trigger?this.trigger===a.trigger&&this.i===a.i:!1};
r6.prototype.isExpired=function(){return 6E4<(0,g.Q)()-this.B};
r6.prototype.toString=function(){return"heartbeat:"+this.trigger+":"+this.i};g.u(t6,g.sM);g.k=t6.prototype;g.k.xa=function(){x6(this);this.player.hf("heartbeat");g.sM.prototype.xa.call(this)};
g.k.onCueRangeEnter=function(){this.K=!0;v6(this,2E3)};
g.k.ex=function(a){this.heartbeatParams=a;v6(this,2E3)};
g.k.GR=function(a){var b;8===this.player.getPresentingPlayerType()||"UNPLAYABLE"===(null===(b=this.i)||void 0===b?void 0:b.status)&&!this.player.N("stop_heartbeat_on_unplayable_live_videos_killswitch")||(g.U(a.state,2)||g.U(a.state,64)?(x6(this),this.C&&(this.K=!0,v6(this,1E3))):(g.U(a.state,1)||g.U(a.state,8))&&v6(this,2E3))};
g.k.HR=function(){3!==this.player.getPresentingPlayerType()&&v6(this,2E3)};
g.k.getPlayerType=function(){if(8===this.player.getPresentingPlayerType())return 1};
g.k.getVideoData=function(){return this.player.getVideoData(this.getPlayerType())};
g.k.Zi=function(a){switch(a){case 4:case 3:return!1}return!0};
g.k.uA=function(a,b,c){a={trigger:a,reason:b};c&&(a.serializedServerContext=c.additionalLoggingData);g.Fv("heartbeatActionPlayerTransitioned",a)};
g.k.Ce=function(a){var b="LICENSE",c=JXa(a);if(c)return c.reason||g.WM[b]||"";(a=a.match(KXa))&&(a=Number(a[1]))&&(b=g.rwa(a));return g.WM[b]||""};
g.k.Ew=function(){return!!this.offlineSlate&&this.offlineSlate.ub};
var KXa=/^GLS\/1.0 (\d+) (\w+).*?\r\n\r\n([\S\s]*)$/;g.rM("heartbeat",t6);})(_yt_player);
