(function(g){var window=this;'use strict';var mXa=function(a,b){a.Qa("onAutonavCoundownStarted",b)},R5=function(a,b,c){g.N(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Se(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.OE&&(b.lengthText?(e=b.lengthText||null,f=b.tq||null):b.lengthSeconds&&(e=g.ZK(b.lengthSeconds),f=g.ZK(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.KE(d).type;var l=b instanceof g.OE?b.isLivePlayback:null,m=b instanceof g.OE?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.Ql||g.iH("Xem $TITLE",{TITLE:b.title}),duration:e,timestamp:f,
url:b.Vk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.un};b instanceof g.NE&&(c.playlist_length=b.playlistLength);a.update(c)},S5=function(a){var b=a.U(),c=b.i;
g.V.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],va:"Tr\u1ef1c ti\u1ebfp"},
{G:"div",Ia:["ytp-autonav-upcoming-stamp"],va:"S\u1eafp di\u1ec5n ra"},{G:"div",L:"ytp-autonav-list-overlay",V:[{G:"div",L:"ytp-autonav-mix-text",va:"T\u1ed5ng h\u1ee3p"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Ia:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});
this.I=a;this.suggestion=null;this.i=c;this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress)},U5=function(a,b){b=void 0===b?!1:b;
g.V.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.J=b;this.D=void 0;this.u=0;b=a.U();var d=b.i;this.I=a;this.suggestion=null;this.onVideoDataChange("newdata",this.I.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.i=new g.V({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{G:"div",
L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.J:""},V:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{G:"div",W:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],va:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],va:"Tr\u1ef1c ti\u1ebfp"},{G:"div",Ia:["ytp-autonav-upcoming-stamp"],
va:"S\u1eafp di\u1ec5n ra"}]},{G:"div",L:"ytp-autonav-endscreen-video-info",V:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});g.H(this,this.i);this.i.Ea(this.element);d||this.T(this.i.Fa("ytp-autonav-endscreen-link-container"),
"click",this.nJ);this.I.Db(this.element,this,115127);this.I.Db(this.i.Fa("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.V({G:"div",L:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.Ea(this.element);this.B=new g.V({G:"div",L:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.Ea(this.element);this.cancelButton=new g.V({G:"button",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"H\u1ee7y t\u1ef1 \u0111\u1ed9ng ph\u00e1t"},
va:"H\u1ee7y"});g.H(this,this.cancelButton);this.cancelButton.Ea(this.B.element);this.cancelButton.Ra("click",this.zR,this);this.I.Db(this.cancelButton.element,this,115129);this.playButton=new g.V({G:"a",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Ph\u00e1t video ti\u1ebfp theo"},va:"Ph\u00e1t ngay"});g.H(this,this.playButton);this.playButton.Ea(this.B.element);this.playButton.Ra("click",this.nJ,this);this.I.Db(this.playButton.element,
this,115130);this.C=new g.J(function(){T5(c)},500);
g.H(this,this.C);this.mJ();this.T(a,"autonavvisibility",this.mJ)},X5=function(a){var b=a.I.Fj(!0,a.I.isFullscreen());
g.N(a.element,"ytp-autonav-endscreen-small-mode",a.Cf(b));g.N(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.DB);g.N(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.re());g.N(a.I.getRootNode(),"countdown-running",a.Mh());g.N(a.element,"ytp-player-content",a.I.re());g.xn(a.overlay.element,{width:b.width+"px"});if(!a.Mh()){a.I.re()?V5(a,Math.round(W5(a)/1E3)):V5(a);b=!!a.suggestion&&!!a.suggestion.un;var c=a.I.re()||!b;g.N(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.N(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.WJ(a.B,a.I.re())}},T5=function(a){var b=W5(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);V5(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Mh()?a.select(!0):a.Mh()&&a.C.start()},W5=function(a){var b=a.I.Up();
return 0<=b?b:g.jD(a.I.U().experiments,"autoplay_time")||1E4},V5=function(a,b){b=void 0===b?-1:b;
a=a.i.Fa("ytp-autonav-endscreen-upnext-header");g.Nh(a);if(0<=b){b=String(b);var c="Video ti\u1ebfp theo sau $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Video ti\u1ebfp theo sau $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Fh("Video ti\u1ebfp theo sau $SECONDS".slice(0,d)));var e=g.Eh("span");g.nr(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Sh(e,b);a.appendChild(e);a.appendChild(g.Fh("Video ti\u1ebfp theo sau $SECONDS".slice(d+c.length)));return}}g.Sh(a,"Ti\u1ebfp theo")},Y5=
function(a,b){g.V.call(this,{G:"div",
Ia:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},Z5=function(a){g.V.call(this,{G:"div",
Ia:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",V:[{G:"span",L:"ytp-upnext-header",va:"Ti\u1ebfp theo"},{G:"span",L:"ytp-upnext-title",va:"{{title}}"},{G:"span",L:"ytp-upnext-author",va:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Ph\u00e1t video ti\u1ebfp theo"},V:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},V:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",V:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
va:"T\u1ef1 \u0111\u1ed9ng ph\u00e1t b\u1ecb t\u1ea1m d\u1eebng"}]}]});this.api=a;this.cancelButton=null;this.D=this.Fa("ytp-svg-autoplay-ring");this.B=this.notification=this.i=this.suggestion=null;this.C=new g.J(this.bz,5E3,this);this.u=0;var b=this.Fa("ytp-upnext-cancel");this.cancelButton=new g.V({G:"button",Ia:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"H\u1ee7y t\u1ef1 \u0111\u1ed9ng ph\u00e1t"},va:"H\u1ee7y"});g.H(this,this.cancelButton);this.cancelButton.Ra("click",
this.AR,this);this.cancelButton.Ea(b);this.cancelButton&&this.api.Db(this.cancelButton.element,this,115129);g.H(this,this.C);this.api.Db(this.element,this,18788);b=this.Fa("ytp-upnext-autoplay-icon");this.T(b,"click",this.BR);this.api.Db(b,this,115130);this.oJ();this.T(a,"autonavvisibility",this.oJ);this.T(a,"mdxnowautoplaying",this.bW);this.T(a,"mdxautoplaycanceled",this.cW);g.N(this.element,"ytp-upnext-mobile",this.api.U().isMobile)},nXa=function(a,b){return b?b:0<=a.api.Up()?a.api.Up():g.jD(a.api.U().experiments,
"autoplay_time")||1E4},$5=function(a,b){b=nXa(a,b);
var c=Math,d=c.min;var e=(0,g.Q)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Mh()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Mh()&&a.i.start()},a6=function(a){Y5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.V({G:"div",L:"ytp-suggestion-panel",V:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"Video kh\u00e1c"}]});this.K=new g.V({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new U5(this.player);g.H(this,this.u);this.u.Ea(this.element);a.getVideoData().wc?this.i=this.u:(this.i=new Z5(a),g.eM(this.player,this.i.element,4),g.H(this,this.i));this.overlay=new g.V({G:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.Ea(this.element);this.C=new g.qC(this);g.H(this,this.C);g.H(this,this.table);this.table.Ea(this.element);this.table.show();g.H(this,this.K);this.K.Ea(this.table.element);this.hide()},b6=function(a){var b=a.re();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.i&&a.u.hide(),a.table.hide()):(a.u!==a.i&&a.u.show(),a.table.show()))},c6=function(a){Y5.call(this,a,"subscribecard-endscreen");
this.i=new g.V({G:"div",L:"ytp-subscribe-card",V:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",V:[{G:"div",L:"ytp-author-name",va:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.H(this,this.i);this.i.Ea(this.element);var b=a.getVideoData();this.subscribeButton=new g.vN("\u0110\u0103ng k\u00fd",null,"H\u1ee7y \u0111\u0103ng k\u00fd",null,!0,!1,b.lj,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.Ea(this.i.Fa("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.La);this.La();this.hide()},d6=function(a){var b=a.U(),c=g.Tz||g.SD?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.V.call(this,{G:"a",Ia:e,W:{href:"{{url}}",target:d?b.J:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",V:[{G:"span",L:"ytp-videowall-still-info-bg",V:[{G:"span",L:"ytp-videowall-still-info-content",W:c,V:[{G:"span",L:"ytp-videowall-still-info-title",va:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",va:"Tr\u1ef1c ti\u1ebfp"},{G:"span",L:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],V:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Danh s\u00e1ch ph\u00e1t",{G:"span",L:"ytp-videowall-still-listlabel-length",V:[" (",{G:"span",va:"{{playlist_length}}"},")"]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],V:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"T\u1ed5ng h\u1ee3p",{G:"span",L:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.i=new g.qC(this);g.H(this,this.i);this.Ra("click",this.onClick);this.Ra("keypress",this.onKeyPress);this.i.T(a,"videodatachange",this.onVideoDataChange);a.Ug(this.element,this);this.onVideoDataChange()},e6=function(a){Y5.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.S=null;this.u=new g.qC(this);g.H(this,this.u);this.J=new g.J(function(){g.L(b.element,"ytp-show-tiles")},0);
g.H(this,this.J);var c=new g.V({G:"button",Ia:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Tr\u01b0\u1edbc"},V:[g.cK()]});g.H(this,c);c.Ea(this.element);c.Ra("click",this.FR,this);this.table=new g.TJ({G:"div",L:"ytp-endscreen-content"});g.H(this,this.table);this.table.Ea(this.element);c=new g.V({G:"button",Ia:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Ti\u1ebfp theo"},V:[g.dK()]});g.H(this,c);c.Ea(this.element);c.Ra("click",this.ER,this);a.getVideoData().wc?this.i=new U5(a,!0):
this.i=new Z5(a);g.H(this,this.i);g.eM(this.player,this.i.element,4);this.hide()},f6=function(a){return g.fM(a.player)&&a.qv()&&!a.C},g6=function(a){var b=a.re();
b!==a.K&&(a.K=b,a.player.ea("autonavvisibility"))},h6=function(a){g.sM.call(this,a);
var b=this;this.endScreen=null;this.i=this.u=this.B=!1;this.listeners=new g.qC(this);g.H(this,this.listeners);this.env=a.U();oXa(a)?(this.B=!0,pXa(this),this.i?this.endScreen=new a6(a):this.endScreen=new e6(this.player)):this.env.me?this.endScreen=new c6(this.player):this.endScreen=new Y5(this.player);g.H(this,this.endScreen);g.eM(this.player,this.endScreen.element,4);qXa(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.Ny("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.T(a,g.Oy("endscreen"),function(c){b.onCueRangeExit(c)})},pXa=function(a){var b=a.player.getVideoData();
if(!b||a.i===b.Si&&a.u===b.wc)return!1;a.i=b.Si;a.u=b.wc;return!0},oXa=function(a){a=a.U();
return a.Lb&&!a.me},qXa=function(a){a.player.hf("endscreen");
var b=a.player.getVideoData();b=new g.Ly(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Ly(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Od([b,c])};
g.YL.prototype.Up=g.ca(3,function(){return this.app.Up()});
g.UX.prototype.Up=g.ca(2,function(){return this.getVideoData().vO});g.u(S5,g.V);S5.prototype.select=function(){(this.I.hk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Mv||void 0)||this.I.N("web_player_endscreen_double_log_fix_killswitch"))&&this.I.wb(this.element)};
S5.prototype.onClick=function(a){g.PM(a,this.I,this.i,this.suggestion.sessionData||void 0)&&this.select()};
S5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Gu(a)||(this.select(),g.Fu(a))}};g.u(U5,g.V);g.k=U5.prototype;g.k.Gy=function(a){this.suggestion!==a&&(this.suggestion=a,R5(this.i,a),this.playButton.Pa("url",this.suggestion.Vk()),X5(this))};
g.k.Mh=function(){return 0<this.u};
g.k.Xt=function(){this.Mh()||(this.u=Date.now(),T5(this),mXa(this.I,W5(this)),g.N(this.I.getRootNode(),"countdown-running",this.Mh()))};
g.k.Fq=function(){this.Um();T5(this);var a=this.i.Fa("ytp-autonav-endscreen-upnext-header");a&&g.Sh(a,"Ti\u1ebfp theo")};
g.k.Um=function(){this.Mh()&&(this.C.stop(),this.u=0)};
g.k.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.Um()};
g.k.nJ=function(a){g.PM(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.wb(this.playButton.element):a.currentTarget===this.i.Fa("ytp-autonav-endscreen-link-container")&&(a=this.i.Fa("ytp-autonav-endscreen-link-container"),this.I.eb(a,!0),this.I.wb(a)),this.select())};
g.k.zR=function(){this.I.wb(this.cancelButton.element);g.$L(this.I,!0);this.D&&this.I.Qa("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){a=b.yZ;this.D=null===a||void 0===a?void 0:a.command};
g.k.mJ=function(){var a=this.I.re();this.J&&this.ub!==a&&g.WJ(this,a);X5(this);this.I.eb(this.element,a);this.I.eb(this.cancelButton.element,a);this.I.eb(this.i.Fa("ytp-autonav-endscreen-link-container"),a);this.I.eb(this.playButton.element,a)};
g.k.Cf=function(a){return 400>a.width||459>a.height};g.u(Y5,g.V);g.k=Y5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.qv=function(){return!1};
g.k.re=function(){return!1};
g.k.kM=function(){return!1};g.u(Z5,g.V);g.k=Z5.prototype;g.k.bz=function(){this.notification&&(this.C.stop(),this.xc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.Gy=function(a){this.suggestion=a;R5(this,a,"hqdefault.jpg")};
g.k.oJ=function(){g.WJ(this,this.api.re());this.api.eb(this.element,this.api.re());this.api.eb(this.Fa("ytp-upnext-autoplay-icon"),this.api.re());this.cancelButton&&this.api.eb(this.cancelButton.element,this.api.re())};
g.k.kW=function(){window.focus();this.bz()};
g.k.Xt=function(a){var b=this;this.Mh()||(g.Vu("a11y-announce","Ti\u1ebfp theo "+this.suggestion.title),this.u=(0,g.Q)(),this.i=new g.J(function(){$5(b,a)},25),$5(this,a),mXa(this.api,nXa(this,a)));
g.qr(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.V.prototype.hide.call(this)};
g.k.Mh=function(){return!!this.i};
g.k.Fq=function(){this.Um();this.u=(0,g.Q)();$5(this);g.L(this.element,"ytp-upnext-autoplay-paused")};
g.k.Um=function(){this.Mh()&&(this.i.dispose(),this.i=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.U().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.bz(),this.notification=new Notification("Ti\u1ebfp theo",{body:this.suggestion.title,icon:this.suggestion.Se()}),this.B=this.T(this.notification,"click",this.kW),this.C.start())}this.Um();this.api.nextVideo(!1,a)};
g.k.BR=function(a){!g.Rh(this.cancelButton.element,g.Bu(a))&&g.PM(a,this.api)&&(this.api.re()&&this.api.wb(this.Fa("ytp-upnext-autoplay-icon")),this.select())};
g.k.AR=function(){this.api.re()&&this.cancelButton&&this.api.wb(this.cancelButton.element);g.$L(this.api,!0)};
g.k.bW=function(a){this.api.getPresentingPlayerType();this.show();this.Xt(a)};
g.k.cW=function(){this.api.getPresentingPlayerType();this.Um();this.hide()};
g.k.xa=function(){this.Um();this.bz();g.V.prototype.xa.call(this)};g.u(a6,Y5);g.k=a6.prototype;g.k.create=function(){Y5.prototype.create.call(this);this.C.T(this.player,"appresize",this.Wu);this.C.T(this.player,"onVideoAreaChange",this.Wu);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.pJ);this.C.T(this.player,"autonavcancel",this.CR);this.onVideoDataChange()};
g.k.show=function(){Y5.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.$L(this.player,!1);g.fM(this.player)&&this.qv()&&!this.B?(b6(this),2===this.videoData.autonavState?this.player.U().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Xt():3===this.videoData.autonavState&&this.i.Fq()):(g.$L(this.player,!0),b6(this));this.Wu()};
g.k.hide=function(){Y5.prototype.hide.call(this);this.i.Fq();b6(this)};
g.k.Wu=function(){var a=this.player.Fj(!0,this.player.isFullscreen());b6(this);X5(this.u);g.N(this.element,"ytp-autonav-cancelled-small-mode",this.Cf(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.lA(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.xn(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.q(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.q(b.value);b=c.next().value;c=c.next().value;g.N(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.i.Gy(a[0]);this.i!==this.u&&this.u.Gy(a[0]);for(var b=0;b<rXa.length;++b){var c=rXa[b];if(a&&a[c]){this.videos[b]=new S5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,R5(d,c));g.H(this,this.videos[b]);this.videos[b].Ea(this.K.element)}}}this.Wu()}};
g.k.pJ=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.i.Um(),this.ub&&this.Wu()):(this.J=!0,this.re()&&(2===a?this.i.Xt():3===a&&this.i.Fq()))};
g.k.CR=function(a){a?this.pJ(1):(this.B=null,this.J=!1)};
g.k.qv=function(){return 1!==this.videoData.autonavState};
g.k.Cf=function(a){return(910>a.width||459>a.height)&&!this.lA(a)&&!(400>=a.width||360>=a.height)};
g.k.lA=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.re=function(){return this.ub&&g.fM(this.player)&&this.qv()&&!this.B};
var rXa=[1,3,2,4];g.u(c6,Y5);c6.prototype.La=function(){var a=this.player.getVideoData();this.i.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.lj;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.u(d6,g.V);d6.prototype.select=function(){(this.api.hk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Mv||void 0)||this.api.N("web_player_endscreen_double_log_fix_killswitch"))&&this.api.wb(this.element)};
d6.prototype.onClick=function(a){g.PM(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
d6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.Gu(a)||(this.select(),g.Fu(a))}};
d6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.u=a.D?!1:b.i};g.u(e6,Y5);g.k=e6.prototype;g.k.create=function(){Y5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Il();this.u.T(this.player,"appresize",this.Il);this.u.T(this.player,"onVideoAreaChange",this.Il);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.SC);this.u.T(this.player,"autonavcancel",this.DR);a=this.videoData.autonavState;a!==this.S&&this.SC(a);this.u.T(this.element,"transitionend",this.AX)};
g.k.destroy=function(){g.sx(this.u);g.Re(this.stills);this.stills=[];Y5.prototype.destroy.call(this);g.qr(this.element,"ytp-show-tiles");this.J.stop();this.S=this.videoData.autonavState};
g.k.qv=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){Y5.prototype.show.call(this);g.qr(this.element,"ytp-show-tiles");this.player.U().isMobile?g.br(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.$L(this.player,!1);f6(this)?(g6(this),2===this.videoData.autonavState?this.player.U().N("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.i.select(!0):this.i.Xt():3===this.videoData.autonavState&&this.i.Fq()):(g.$L(this.player,!0),g6(this))};
g.k.hide=function(){Y5.prototype.hide.call(this);this.i.Fq();g6(this)};
g.k.AX=function(a){g.Bu(a)===this.element&&this.Il()};
g.k.Il=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.L(this.element,"ytp-endscreen-paginate");var a=this.I.Fj(!0,this.I.isFullscreen()),b=g.VL(this.I);b&&(b=b.Ze()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),h=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<h);){var p=b/2,r=e/2,t=b<=f-2&&n>=r*m,v=e<=h-2&&n>=p*m;if((p+
1)/r*d/c>c/(p/(r+1)*d)&&v)n-=p*m,e+=2;else if(t)n-=r*m,b+=2;else if(v)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Hn(a,m,n);g.xn(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.i.Gy(this.videoData.suggestions[0]);this.i instanceof U5&&X5(this.i);g.N(this.element,"ytp-endscreen-takeover",f6(this));g6(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(h=0;h<e;h++)if(p=c,r=0,d&&f>=b-2&&h>=e-2?r=1:0===h%2&&0===f%2&&(2>h&&2>f?0===h&&0===f&&(r=2):r=2),p=g.Sg(p+this.B,l),0!==r){t=this.stills[c];t||(t=new d6(this.player),this.stills[c]=t,a.appendChild(t.element));v=Math.floor(n*h/e);var x=Math.floor(m*f/b),y=Math.floor(n*(h+r)/e)-v-4,z=Math.floor(m*(f+r)/b)-x-4;g.Dn(t.element,x,v);g.Hn(t.element,z,y);g.xn(t.element,"transitionDelay",(h+f)/20+"s");g.N(t.element,"ytp-videowall-still-mini",1===r);g.N(t.element,"ytp-videowall-still-large",
2<r);r=t;p=this.videoData.suggestions[p];r.suggestion!==p&&(r.suggestion=p,t=r.api.U(),v=g.or(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",R5(r,p,v),g.UD(t)&&(t=p.Vk(),t=g.Gj(t,g.NL("emb_rel_end")),r.Pa("url",t)),(p=(p=p.sessionData)&&p.itct)&&r.api.Zj(r.element,p));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Ph(e.element),g.Qe(e);this.stills.length=c}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Il())};
g.k.ER=function(){this.B+=this.stills.length;this.Il()};
g.k.FR=function(){this.B-=this.stills.length;this.Il()};
g.k.kM=function(){return this.i.Mh()};
g.k.SC=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.i.Um(),this.ub&&this.Il()):(this.D=!0,this.ub&&f6(this)&&(2===a?this.i.Xt():3===a&&this.i.Fq()))};
g.k.DR=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.eb(this.stills[a].element,!0);this.SC(1)}else this.C=null,this.D=!1;this.Il()};
g.k.re=function(){return this.ub&&f6(this)};g.u(h6,g.sM);g.k=h6.prototype;g.k.Sq=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!oXa(this.player)||b;var c=a.Je||g.eE(a.B),d=this.player.Sv();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.re=function(){return this.endScreen.re()};
g.k.aU=function(){return this.re()?this.endScreen.kM():!1};
g.k.xa=function(){this.player.hf("endscreen");g.sM.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.zM;if(b&&b.videoId){var c=this.player.vb().Md.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.DJ?a=!1:(this.player.hk(b.videoId,void 0,void 0,!0,!0,b),c&&c.uA("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.sM.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.sM.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Sq()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){qXa(this);this.B&&pXa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.i?this.endScreen=new a6(this.player):this.endScreen=new e6(this.player),g.H(this,this.endScreen),g.eM(this.player,this.endScreen.element,4))};g.rM("endscreen",h6);})(_yt_player);
